### ISSUE TITLE
Soujourner's Sash prevents block.onFallenUpon()

### ISSUE THREAD

**Issue by AEnterprise** [Vazkii/Botania#1027]
some of the BCA dusters require players to jump on them, when the have a sash equiped the block.onFallenUpon function doesn't get called

BCA issue reference: https://github.com/BCA-Team/Buildcraft-Additions/issues/422

**Comment by TheWhiteWolves** [comment]
It's most likely because of the fall dampening of the sash, it looks like onFallenUpon() fires after you fall a certain distance, which if that's the case without removing the dampening there not likely to be a fix for it unless vanilla changes how it does it.

You can either remove the sash when you want to use it or fall from a greater height, which should then activate it, by default the soujouners sash it set with a 2 block fall buffer so try adding that distance to your drop height and see if it works then if you would.

**Comment by AEnterprise** [comment]
i can't do that, the function doesn't get called at all, in my code i don't care about the fall distance so the function doesn't get called on my end at all so for me there is no way of detecting it

**Comment by TheWhiteWolves** [comment]
does it not get called when you are not wearing the sash?

**Comment by AEnterprise** [comment]
it should get called when you are not wearing the sash, i didn't find the bug myself, i'm the BCA dev and the bug was reported to me but as you see in the report he sais he is wearing the sash, the bug is certainly not present without botania so it must be the sash itself preventing the code from getting called

**Comment by TheWhiteWolves** [comment]
Are you able to try it with Botania installed but not wearing the sash?, I'm at work so I'm not near any systems that I can check it on.

Unfortunately I don't think there is a way around it in either your mod or Botania as my suspicion is that it is the fall distance, even though you yourself don't use the fall distance the onFallenUpon() function from MC's Block class does, which would lead to it not calling the function unless you fall enough distance, which due to the fall buffer of the sashes means that needs to be a larger distance than when not wearing them.

**Comment by TheWhiteWolves** [comment]
Only thing I can think of as a solution is if there is a forge event or something similar that can be triggered or a function called either on your end or botania's end to get it to work but as I said I wont be able to look into that until tonight.

**Comment by AEnterprise** [comment]
i'm at school so also unable to check but i'll test it when i get home but it indeed makes sense that the sash buffer is messing with it

**Comment by AEnterprise** [comment]
alright, the reporter verified that it works without the sash, are you gona make some integration as workaround or just close it and tell people not to use it?

**Comment by TheWhiteWolves** [comment]
I'll try and have a play around with it tonight and see if I can find some way to get it to fire, if not we'll probably have to close it for now until we can think of a way around it.

**Comment by AEnterprise** [comment]
alright it's no problem if it stays like this, i can just put a note on the wiki about it

**Comment by Vazkii** [comment]
Not fixing.

**Comment by AEnterprise** [comment]
alright, i'll just put a note on wiki page, could that maybe also be somewhere in the info on the sash so people know it might cause issues with block that react to jumping?
