### ISSUE TITLE
Agricarnation does not fertilize forestry fruit leaves

### ISSUE THREAD

**Issue by spamael** [Vazkii/Botania#1042]
I just updated FTB Infinity from 1.3.4 to 1.5.1 which brought Botania upgrade from r1.5-170 to r1.6-184.
I was using the agricarnation flower to boost up my forestry orchard (for seed oil production) and noticed it didn't work anymore. 
I read the changelogs between those two versions and saw that there was a change related to agricarnation:
"Agricarnations will only fertilize blocks that can normally be grown with bone meal." 
However, I (still) can fertilize leaves with bone meal, but agricarnation just leaves (pun intended) them be. I'm not sure if this is the desired behaviour and have not find any more information related to this.

**Comment by TheWhiteWolves** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
