### ISSUE TITLE
Black Hole Talisman places blocks in player's head.

### ISSUE THREAD

**Issue by devemouse** [Vazkii/Botania#1043]
When placing blocks "normally" I cant place a block in such way that I suffocate.
If placed with talisman, I can completely cover my player with blocks.
I suggest adding an entry in Lexicon that it is also a burial tool ;)

Botania 190.

**Comment by Entoarox** [comment]
Yeah, the "is entity occupying part of this block space" check seems to be missing, but I was thinking it intentionally left that way since the code was copied from TT and thus the issue should have been caught there already (unless vazkii forgot to copy something when stealing the code from herself?)
