### ISSUE TITLE
Greater Band of Mana losing Mana

### ISSUE THREAD

**Issue by ArfourFoulkesayke** [Vazkii/Botania#1074]
I am not sure if this is a bug but my Greater Band of Mana is losing Mana while I am logged off. I noticed this yesterday after an automatic server restart and today after logging in. Yesterday the band was completely depleted, today my nearly full band was drained to about 5 %.

Both times I logged off standing on the ground. I am currently using the following baubles: Flügel Tiara, Soujourner's Sash and said Greater Band of Mana. No armour, no weapons.

We are playing on a direwolf_20 pack, version 1.0.3, Botania version 1.84.

**Comment by MrKunji** [comment]
If you don't try to reproduce on the latests version, close the issue.

**Comment by TheWhiteWolves** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
