### ISSUE TITLE
Chisel 2 Compatibility Issue

### ISSUE THREAD

**Issue by Keyarose** [Vazkii/Botania#1084]
The default recipe for Chisel 2's diamond chisel is overridden by the diamond trowel.
[e][d]
[s][e]
e- empty
s- stick
d- diamond

There is an alternative recipe that can be enabled in Chisel 2's config, unfortunately that quadruples the cost of making it.

**Comment by MyDeloreanWontStart** [comment]
Am I retarded or does this have ntohing to do with botania

**Comment by TheWhiteWolves** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*

**Comment by Keyarose** [comment]
Sorry misread the mod tag on the tooltip, it's binnie's botany trowel.
