### ISSUE TITLE
Thermalilies + TiMech Drawbridges = bye bye delay

### ISSUE THREAD

**Issue by VolterPL** [Vazkii/Botania#1086]
I know Botania flowers are intelligent enough to not have their delay reset by being broken and replaced by a player, but that's not the case if one's using Tinkers Mechworks' Drawbridges. Not that it's that bad to have such an op flower in mana generating flowers arsenal, but I'm too honest to not report that.

Version: 190

Tested with a basic Drawbridge and a Floating Thermalily.

**Comment by MrKunji** [comment]
Can you reproduce in Botania 192? Is Mechworks in the latest stable version?

**Comment by Entoarox** [comment]
@MrKunji The drawbridges do not actually break the block the way a fake player would, thus the delay is not getting saved to NBT, the fix here would be to make the delay part of the NBT from the get-go, and not only when the block is asked for its dropped itemstacks, but since NBT is rather slow, that might cause more problems then it fixes.

**Comment by Vazkii** [comment]
Can the drawbridges break Thaumcraft jars properly? If not then this is on their end. Please update the  issue if you figure that out. You can comment on closed issues.
