### ISSUE TITLE
Mana Blaster with Force Lens can move Bedrock

### ISSUE THREAD

**Issue by 016Nojr** [Vazkii/Botania#1115]
The title says it all.

Using Agrarian Skies 2 1.1.6, which uses version r1.6-191

**Comment by TheWhiteWolves** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*

**Comment by Vazkii** [comment]
This issue looks pretty legit.

**Comment by TheWhiteWolves** [comment]
I assume it's happening in the latest version as well but we'll need to check
