### ISSUE TITLE
Botania.sign-1 is not an astrological sign.

### ISSUE THREAD

**Issue by auxiliary-character** [Vazkii/Botania#1126]
![](http://i.imgur.com/l6Rngta.png)

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*

**Comment by auxiliary-character** [comment]
Sorry about that, I didn't see those rules there. Let's try this again.

Occasionally if you spin clockwise while opening the Eye of the Flügel, there's a small space on the right edge of the Aries region that demonstrates the behavior shown in the screenshot.

I have recreated this in a test environment with only the latest Forge, Botania, and Baubles:

![](http://i.imgur.com/4SoPjJ4.png)

Here's the [FML log](https://gist.github.com/auxiliary-character/30efad06008e5f1b9ec6).

**Comment by Vazkii** [comment]
Interesting.

**Comment by Zsashas** [comment]
Does it still function as part of the Aries section, or a separate one?

**Comment by MyDeloreanWontStart** [comment]
WHEN -1 RISES A GOAT WILL BE BORN WITH THREE HEADS TO A TISSUE BOX WITH LEGS.

this is why this must be fixed

**Comment by auxiliary-character** [comment]
It functions as a separate one.

**Comment by Durpady** [comment]
Call it Ophiuchus?

**Comment by Nanoqtran** [comment]
I find this only happens when that specific section is pointing east
