### ISSUE TITLE
Lexica Botania challenges "Info" button causes crash

### ISSUE THREAD

**Issue by bloop428** [Vazkii/Botania#1133]
The button that says "Info" near the bottom right of ANY challenge page in the Lexica Botania causes a crash when clicked. There isn't much more to say, so here is an image and FML Log.

FML Log: http://pastebin.com/3wyduudQ

![2015-06-29_16 11 41](http://i.imgur.com/xDccLRU.png)

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*

**Comment by bloop428** [comment]
EDITED - Sorry Vazkii, it's my first bug report :3

**Comment by MrKunji** [comment]
Reproduced with success in Botania 196, but couldn't copy the crash log.
