### ISSUE TITLE
Getting Stuck On Blocks Broken By Gaia Guardian

### ISSUE THREAD

**Issue by RoloEdits** [Vazkii/Botania#1138]
When Fighting The GG I Get Stuck In The locations Were It Broke Blocks And Also Items Fall From The Breaking And get In The Magnet And Yet I Cant Pick Them Up

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
