### ISSUE TITLE
Gaia Guardian 2 breaks blocks clientside

### ISSUE THREAD

**Issue by vpzomtrrfrt** [Vazkii/Botania#1141]
I was trying to fight the Gaia Guardian 2, but it started breaking a lot of blocks on the client only.  This led to getting stuck in blocks that I fell into that were actually there, and ghost items following me around (Ring of Magnetization).  This didn't happen the last time I tried it, before the recent updates.  I haven't tried it on the first Guardian since then yet.
![2015-07-02_18 31 23](https://cloud.githubusercontent.com/assets/3528358/8490985/c95e0072-20ef-11e5-96e2-8fc6f70ee898.png)

FML Log: https://dl.dropboxusercontent.com/u/79626245/guardianbuglog.txt

**Comment by Entoarox** [comment]
Looks like there is a missing check for `worldObj.isRemote` around https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/entity/EntityDoppleganger.java#L397 when it executes the code for destroying the block, meaning it it executed both server and client-side instead of only on the server-side.
