### ISSUE TITLE
[Bug] Hopperhock deletes items instead of putting them in FZ Barrels.

### ISSUE THREAD

**Issue by BarbasTheDog** [Vazkii/Botania#1142]
Title says it all, really.

**Comment by TheMadmanofChaos** [comment]
Please read the contributing guild lines, located here. https://github.com/Vazkii/Botania/blob/master/contributing.md

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*

**Comment by BarbasTheDog** [comment]
Vazkii, fix yo macro! This is a perfectly valid issue.

**Comment by TheWhiteWolves** [comment]
No its not a valid issue, how about you go off and actually read the contributing guidelines then come back

**Comment by BarbasTheDog** [comment]
OP updated to reflect the rule of the Internet that says "Assume everyone you don't know is an idiot."

**Comment by TheMadmanofChaos** [comment]
As a future note, listing the exact version is better then "Latest". We've had people say "Latest", and have outdated versions due to recent updates.

**Comment by BarbasTheDog** [comment]
Fair enough. Updated OP.
