### ISSUE TITLE
(Minor) Pure Daisy high inactive latency

### ISSUE THREAD

**Issue by Flamarow** [Vazkii/Botania#1145]
Not much of a problem but the Pure Daisy requires 10-15 microseconds update time when it is surrounded by blocks regardless of if the blocks are valid for transforming into other forms. When it is surrounded by only air blocks, it uses less than 2 microseconds so I am not sure why uses so much when surrounded by living stone or dirt. 

Tested using Opis. Currently the pure daisy ranks in the top 5 singular tile entities when it has 8 blocks around it.

**Comment by Entoarox** [comment]
Latency is caused by the pure daisy needing to check if the block is valid for conversion into another one, this check is skipped for air blocks. @Vazkii Perhaps having it go into a sleep state for a second or two when none of the eight blocks around it can be converted, or maybe some form of quick-to-access cache on what the valid recipes are? (Is that even possible with java? I am not nearly experienced enough with it to know.)

**Comment by Vazkii** [comment]
I can make the algorithm more performant, I'll take care of that later.
