### ISSUE TITLE
Gaia Guardian on gamerule mobGriefing false

### ISSUE THREAD

**Issue by LukasXD01** [Vazkii/Botania#1147]
If you have set the gamerule mobGriefing false and spawn the gaia guardian it looks on your client as if it would break blocks and it drops the items but the blocks just disappear (if you relog they're there again) and you can't pick up the dropped items and they don't despawn.They only disappear if you relog.

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
