### ISSUE TITLE
Blocks brocjen by the Guardian of the Gaia lose their meta-data

### ISSUE THREAD

**Issue by SuperSandro2000** [Vazkii/Botania#1153]
I tries to build a little deco wall with railcrafts brick walls and every time the guardian ports itself into them they breack in fitted abyselstone walls. This is wall variant with no meta data.

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*

**Comment by TomeWyrm** [comment]
The Gaia Guardian's teleport block break (the bear trap cheese prevention) does not respect metadata (I did not test NBT, but can if you would like. I don't see how it would respect NBT and not the damage value/metadata).

You can reproduce by making (and using) a Gaia Guardian arena in a superflat with this preset: 2;7,44:7;0;

The only important portion of the string is finishing the block section with "44:<number greater than 0>".

When the guardian teleports on top of a slab, it will break the slabs on the ground and they will be Stone Slabs(44:0), not whichever slab you put on the ground.

FML Log: http://pastebin.com/23JpM7g4
