### ISSUE TITLE
More More Health with Ring

### ISSUE THREAD

**Issue by BlayzerQ** [Vazkii/Botania#1165]
https://pp.vk.me/c627121/v627121100/b518/Vv4CjAWPcj4.jpg
https://pp.vk.me/c627121/v627121100/b52c/iOTW9qfm9gY.jpg
Crafted a great ring to throw for themselves.He returned back to 3 rings. Dress, etc.
HP remain on the player, added new ones.

**Comment by MrKunji** [comment]
Provide more information, only this can't explain what's going on

**Comment by TheWhiteWolves** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
