### ISSUE TITLE
Augment Dupe Bug!

### ISSUE THREAD

**Issue by SneakyDevil** [Vazkii/Botania#1182]
Was placing spark augments on the spark tinker block, accidentally clicked twice and it gave me a full stack of that augment, and continues to do so every time i click it...

Edit: each tinker block used in conjunction with said dupe also appears to contain a full stack of said augments.

fml log: http://puu.sh/j3kek/a1fd051075.log

**Comment by TheWhiteWolves** [comment]
Extra Info: 
1) On right-click it places one item from the entire stack you are holding into the tinkerer (i.e. removes one from the stack amount in your hand) however the stack in the tinkerer is set to the amount you are holding instead of a single item, meaning that when you click to remove it you double the amount you have.

2) If you click with the stack in your hand while an augment is in the tinkerer you gain the amount in the tinkerer but don't remove the augment from it,

**Comment by Michael1992** [comment]
I did some further testing botania version 202   Dupe only seems to work with dominant and recessive sparks

-A
