### ISSUE TITLE
Ring of far reach not properly working

### ISSUE THREAD

**Issue by BurningEagle** [Vazkii/Botania#1187]
When equipping the Ring of far reach it doesn't always seem to work. Throwing it on the ground and picking it back up and reequiping it doesn't help either. Relogging does work however, but again, not always. 

I've also encountered a bug which gave me a little bit to far reach, up to about 2 chunks (I haven't been able to measure this well). With Waila I was able to see the information of blocks from insane distances and be able to access and place blocks. 

I removed all my items except the ring and the bug was still happening, even after I removed the ring itself it still occurred. Note how these bugs only started occurring after I made the ring, befor that it had never happened with tens of hours spent on the game with no updates in between. 

I'm using the latest version of the Direwolf20 modpack with version 1.7.10

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
