### ISSUE TITLE
Already Tesselating error

### ISSUE THREAD

**Issue by Saereth** [Vazkii/Botania#1202]
After updating to V204 getting a client crash with Alredy Tesselating when near the alfportal.
Here is my pastebin
http://pastebin.com/sf5TH6Q9

Happy to provide any additional info.

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
