### ISSUE TITLE
Problem with Mana Distributor

### ISSUE THREAD

**Issue by w3ricardo** [Vazkii/Botania#1203]
The Mana Distributor doesn't seem to be filling a Mana Pool next to it that has a Natura Pylon.

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
