### ISSUE TITLE
Slimeball alchemy eats first ball

### ISSUE THREAD

**Issue by Periosa** [Vazkii/Botania#1213]
When using the alchemy catalyst thingy (technical terms here) to turn slimeballs into cactus, one less cactus is received than expected.

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
