### ISSUE TITLE
Random server freezes

### ISSUE THREAD

**Issue by oleg599** [Vazkii/Botania#1225]
Hi,

I got random server freezes when players use a spreaders, analyzed lag spikes via WarmRoast and got TileSpreader (screenshot - https://monosnap.com/file/IZYybqar9HmOiu6WDaJHLwKZ8OFIOY). Same is for EntityManaBurst-based items (ex. Terra Sword, superUpdate method).

Botania 208 (without Garden of Glass), MC 1.7.10, Forge 1492.

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
