### ISSUE TITLE
Crafty Crate

### ISSUE THREAD

**Issue by WyvernArchmage** [Vazkii/Botania#1231]
Crafty Crate. 1x1 Template
Wood Logs = Wood Planks

Works fine, unless it's dropping into a hopper directly. 
Then it reduces every log into a single plank.

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
