### ISSUE TITLE
Tall Flowers Drop Different Type Sometimes

### ISSUE THREAD

**Issue by RoloEdits** [Vazkii/Botania#1246]
When breaking a tall mystical flower, with bedrock shears if it makes any difference, I occasionally get a different type then the one I broke eg. breaking a tall red drops a tall grey.

**Comment by MrKunji** [comment]
Not enough information.

**Comment by RoloEdits** [comment]
what other info should I provide? When breaking a tall mystical flower it does not always drop the kind that you broke, for example when breaking a tall red flower instead of dropping a tall red flower it drops a tall grey flower. I'm not sure what other information I can provide.if describing it is not enough to visualize it do I need screenshots or a video?FML?

**Comment by RoloEdits** [comment]
I'm not even sure were to begin looking for the problem.I'm using version Botania r1.7-208,the shears I was using are the bedrock shears from rotary craft RotaryCraft 1.7.10 V7f.

**Comment by Entoarox** [comment]
Does the problem occur only with bedrock shears, or does it also occur with other kinds of shears? If it does, are the vanilla shears included in this?
Right now all you have told us is "When harvesting tall magic flowers with bedrock shears stuff goes wrong", but without more details it can be anything from a typo in botania, a typo in the mod that bedrock shears come from, a mod interaction bug, or herobrine messing with your mind. (He never got removed really, he just hid out in the old code and messes with our mods now....)

**Comment by RoloEdits** [comment]
after reading your comment i feel like an idiot.i'm sorry please forgive my stupidity.i'll check right know  with all other shears.

**Comment by RoloEdits** [comment]
as far as i can tell it seems to be with just the bedrock shears. I tested the botania mana steel ones as well as the dark steel and vanilla shears and the Bound Shears from blood arsenal.I even tested the hsla steel shears from rotarycraft but they work fine too.

**Comment by Entoarox** [comment]
What mod are the bedrock shears from? You might need to report this issue to the creator of that mod, since the issue only seems to occur with their shears.

**Comment by RoloEdits** [comment]
Rotarycraft. I'll report it to him as well.

**Comment by Entoarox** [comment]
Looks like an interaction bug in how rotarycraft's bedrock shears handle metadata of double plants and botania not knowing what rotarycraft needs to get the correct metadata, unless I am greatly mistaken, using the bedrock shears should only drop double flowers with metadata 0~3 (It is four different double tall plants isnt it? grass, and three kinds of flowers right?), since as far as I can tell Botania does not overwrite the list rotarycraft uses to calculate what metadata to drop for double plants, perhaps rotarycraft should change its double-plants handling to query `damageDropped`, but that is best left to the mod author to figure out.

**Comment by Bellwar** [comment]
Im not reading in but i remember in Mod of the Month it didnt drop even one it was pure decorative there but the modpack was so buggy :/

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
