### ISSUE TITLE
Spreader randomly stopping.

### ISSUE THREAD

**Issue by Mach12** [Vazkii/Botania#1248]
Title says it all. I have a spreader that keeps stopping. It's a regular spreader, it's not emptied, its target is far from full, yet it stops at random. Well, seemingly at random, but most of the time it is when I load my game, or after being far away from the spreader.

Also to be noted: I don't know if this matters, but the spreader and the pool it aims for are in distinct chunks that aren't adjacent, the 2 chunks merely share a corner.

[Near view of the setup](http://imgur.com/9YuhXkt)
[View of my full setup from higher](http://imgur.com/rmYa4K8), the red lines are chunk corners verticals

Oh and sorry for originally posting it on Botania's Reddit. Didn't spot the link to GitHub immediately.

**Comment by TheWhiteWolves** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
