### ISSUE TITLE
Daybloom disappearing on it's own

### ISSUE THREAD

**Issue by SythsGod** [Vazkii/Botania#1263]
The dayblooms seem to be disappearing on their own. I couldn't find any possible event or actions triggering it, except perhaps the unloading of the chunk.

If you want a mod list with versions, I would be happy to provide one.

PS: This is the second server I was in where I found this bug happening. I can give you a list for both servers if you specify so.

**Comment by GTMelo** [comment]
It's a new config. Dayblooms and Nightshades wither away after some time. You can specify how long they last, or even disable the effect entirely.

Considering that I've seem other people confused by this (myself included), I think it would be better to  make this withering effect a tad more explicit. Maybe instead of having the flowers disappear, change them to a "withered flower" or something along these lines.

**Comment by SythsGod** [comment]
I see. Thanks for your quick reply, it's much appreciated.

You're definitely right about the way it's done. A bit more obvious would be useful.
