### ISSUE TITLE
Ring of Loki

### ISSUE THREAD

**Issue by rupeezfodayz99** [Vazkii/Botania#1266]
I put the ring of loki on. Shift right clicked the first block, right clicked a pattern, and right clicked the first block again, as the book said. I then got a stack of blocks and placed one down. And, nothing happened. I tried making the pattern and placing the block in both survival and creative. I don't think this is my own error, so I'm thinking it's a bug

**Comment by MrKunji** [comment]
If it's on Botania v209 (you should have specified the version you're using), the Ring of Loki uses mana now.

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
