### ISSUE TITLE
ArrayOutOfBoundsException

### ISSUE THREAD

**Issue by PigKing107** [Vazkii/Botania#1270]
If you try to give your self a Botania:flower with a data value of 20(and probably other numbers too) the game will crash.

**Comment by MrKunji** [comment]
Botania version? Crash log?

**Comment by PigKing107** [comment]
1.7-201
http://pastebin.com/dswAvNdX

**Comment by MrKunji** [comment]
Try to reproduce on the recent version.

**Comment by TheWhiteWolves** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
