### ISSUE TITLE
Force Relay breaks if Pushed by Piston With Another Force Relay Infront

### ISSUE THREAD

**Issue by HyperionNexus** [Vazkii/Botania#1283]
So I was making a door and a friend suggested to use force relays, so he set it up and it worked for the first movement however, once we tried to push multiple force relays from one piston it would break.

I'm not sure if this is a bug but it would be nice to be a feature if it's meant to be like this.

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
