### ISSUE TITLE
Tiara overwrites flights from other mods. 

### ISSUE THREAD

**Issue by Heheggg** [Vazkii/Botania#1291]
Botania r1.7-211

I enjoy using the tiara for its aesthetics (mega-ultra-chicken) and dash, however its active effect overwrites other mod items that also offers flight (Angel ring, Robes of the Stratosphere).

Limiting the flight restriction to the tiara may need a rework on its mechanic. In case that is too much work, it might be wise creating a aesthetic variant of the tiara that only has the dash.

**Comment by phantamanta44** [comment]
All of the flight items you listed implement flight through Minecraft's built-in flight system, which means turning off flight using one of the items will also turn off flight for all the other items (as well as stopping creative flight).

**Comment by PsiGuy60** [comment]
I think the problem here is in vanilla Minecraft - all the items you listed grant flight through vanilla Minecraft's implementation. Using them all at the same time causes a conflict, and may have all the drawbacks at once (Angel Ring causes you to use food as if you were sprinting, Flügel Tiara's temporary nature and Mana usage).

**Comment by Vazkii** [comment]
Not much I can do about this, really.

**Comment by Barhandar** [comment]
Store value of flight-ability in the tiara, restore it when the flight meter runs out.

**Comment by TheWhiteWolves** [comment]
@Barhandar wouldn't make a difference as the problem is not with how the flight ability is stored its with how it is granted, if I am correct, due to how vanilla functions when botania detects that you are not wearing a tiara it uses player.capabilities.allowFlying = false; to take away your ability to fly

**Comment by Vazkii** [comment]
The extra utils angel ring only sets your flight to true the first tick you put it on for some odd reason, so there isn't much I can do about that.

**Comment by TheWhiteWolves** [comment]
that's probably why it currently has a bug where it stops giving you flight, which coincidentally is fixed by you dropping it and picking it back up
