### ISSUE TITLE
[Suggestion/Missing Ability] A way to remove Shadow Ink from items?

### ISSUE THREAD

**Issue by JAWSAWN** [Vazkii/Botania#1312]
Perhaps like other upgrades to items? Putting the item in the crafting bench and it will lose its tint. If there is already a way let me know.

**Comment by TheWhiteWolves** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
