### ISSUE TITLE
 I can't see the flowers

### ISSUE THREAD

**Issue by YousiVulpeen** [Vazkii/Botania#1326]
I don't know why i can't see the flowers. I installed the mod, Baubles and Colored Lights. I tried on differents survival worlds but nope. Help please, i love this mod and i want to play it seeing the amazing flowers

**Comment by phantamanta44** [comment]
I suspect Colored Lights breaks the rendering of flowers, similarly to OptiFine.

**Comment by YousiVulpeen** [comment]
Oh ok i have Optifine installed

**Comment by MrKunji** [comment]
Colored Lights and Botania should be compatible since Botania version 148.

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
