### ISSUE TITLE
mana spreaders are not updating

### ISSUE THREAD

**Issue by SDUBZ** [Vazkii/Botania#1335]
the latest build is causing the mana spreaders not to update on my server and the velocity lens seems to be the culprit the build im using is build 219

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
