### ISSUE TITLE
Rannucarpus and Farmland

### ISSUE THREAD

**Issue by eslachance** [Vazkii/Botania#1339]
This is related to #1227 and a bit of Google searching that reveals the issue: It's currently not possible to use the Rannucarpus to make an automated farm (wheat, potatoes, carrots, etc). 

Farmland doesn't support having a "block" on top, whether a dirt block or a floating flower.

This is severely hindering my plan to make a botania-only farm that doesn't have 64 blocks to plant seeds :P

**Comment by OJwithC** [comment]
The issue isn't actually the farmland; the rannuncarpus isn't allowed to place seeds, carrots, etc. at all. This can be tested by not setting a filter on the rannuncarpus, or using another mod that provides a block that can be planted on (like garden soil from Ztones; the flower will place sugar cane on it, but not any seeds).
Vazkii tweaked dispensers for a reason.

**Comment by liftoff** [comment]
Botania modifies vanilla dispensers so that they can be used to plant seeds, carrots, potatoes, etc.  That's what you're supposed to use instead of the Rannuncarpus.  The only thing that sucks about the Dispensers is their cost in terms of string (have to make loads of bows to make loads of dispensers).  I know you can make string by dropping wool into an Alchemy Catalyst Mana Pool but that's much later game than I'd like for the ability to plant seeds.

You'll need loads and loads of dispensers to make any sort of reasonably-sized automated farm which is disappointing.  Especially considering that Botania has no way to detect when plants are fully grown.  You just sort of have to put a really long timer (say, 30 minutes) on the Hovering Hourglass and hope for the best.  Using loads of Agricarnations could help reduce the growth time I guess.

**Comment by eslachance** [comment]
So basically, doing a botania-only farm without a complex redstone, item moving and dispenser system is never going to happen. Sad. Then we wonder why people always do MFR farms.
