### ISSUE TITLE
Lexica Botania Stuck

### ISSUE THREAD

**Issue by Drakynnan** [Vazkii/Botania#1341]
It seems somehow (and I don't know how to replicate this) the Lexica becomes stuck on whatever pager you were looking at and when trying to return to its index, the book exits and the crosshair turns into a transparent square (with the book and question mark thingy) and you can do nothing else with it

**Comment by TheWhiteWolves** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*

**Comment by TheWhiteWolves** [comment]
Mainly list of mods/versions etc.

Also do you have Tinkers installed as that transparent square sounds like the Tinkers crosshair.

**Comment by Drakynnan** [comment]
Mod List:
http://imgur.com/IEbYak7

And no, I haven't bothered to get Tinkers yet. If I get the issue again I'll post a screenshot, but for now, I still don't know how it happens or how I managed to fix it. Its happened twice so far though
