### ISSUE TITLE
Flower Pouch does not automatically pull flowers into itself.

### ISSUE THREAD

**Issue by Zsashas** [Vazkii/Botania#1344]
This is on a server, by the way.

It doesn't matter whether it has that color in it already or not, they always go into my inventory instead. Tested with several colors, in various dimensions, with a full and empty inventory.

**Comment by TheWhiteWolves** [comment]
are you holding the bag when you try to do this?

**Comment by Zsashas** [comment]
No. The bag is in my main inventory. Also, very rarely, it DOES pull flowers in automatically, but I am unable to notice a pattern.

**Comment by TheWhiteWolves** [comment]
does it does this when you have only botania installed?

**Comment by p455w0rd** [comment]
I'm getting the same thing. Yes other mods installed (181 total) check p455w0rdCraft 2.0 on technic for list. No magnet or anything of the sort in inventory. I break them with the bag in hand, same result. No botania errors in server log. Only bauble is Extra Utilities wings ring. Plus TiC knapsack and heart canisters in TiC inventory.

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*

**Comment by Zsashas** [comment]
Seems to be working ONLY when my inventory is completely packed full, but still not 100% of the time. Botania version 221, different pack than the original situation but same issue appears.
