### ISSUE TITLE
Flower Duplication Bug (using bag)

### ISSUE THREAD

**Issue by 1n5aN1aC** [Vazkii/Botania#1348]
You can easily exploit a minor bug in the GUI of the flower pouch to get infinite flowers with very, very little work, and therefore infinite dyes with very, very little work.  Several members on my server have taken to using this bug to generate any dyes that they need, and therefore I am considering banning flower pouches until this is fixed.

Versions:
Tested on Botania v218 & v219
Tested on Forge v1492

Problem:
If you force the flower pouch to be dropped while holding an flower stack in your hand, said flower stack will be duplicated.

Steps to reproduce:
1.  Put flowers in a flower pouch.
2.  Open the flower pouch's GUI.
3.  Pick up a stack of flowers from the pouch onto your mouse cursor.
4.  Drop the flower stack onto the slot where the pouch is currently.  (Picking up the pouch instead.)
5.  The pouch will be dropped on the ground, but will still contain the flowers that you now have in your inventory.

Possible fix:
One fix would be to use a 'locked' item slot in the slot where the bag is, preventing the bag from being moved in any way by the player while the GUI is open.

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*

**Comment by 1n5aN1aC** [comment]
Updated original post to add more information to the already fairly detailed post with reproduction instructions.
