### ISSUE TITLE
Generating Flora and pure daisy dupe bug

### ISSUE THREAD

**Issue by Nicklaspoke** [Vazkii/Botania#1364]
After I had made a pure daisy and planted it. I surrounded it with stone. After the process of creating livingrock was done i destroyed all the livingrock blocks and the pure daisy with a vajra(Gravitation Suite mod) that had silktouch mode turned on(I was right clicking with it). When I right clicked on the pure daisy it dropped 2 pure daisys instead of 1.

Further testing showed that the same thing occurred with nightshade, daybloom, manastar, endoflame, spectrolus, kekimurus, entropinnym, munchdew and rosa arcana.
There can possibly be more flowers that this works for, but I have only tested with these.

FML Log: http://puu.sh/k4bD6/b28fa8f82f.log

**Comment by OJwithC** [comment]
Does something similar happen to things like grass or poppies?

**Comment by Nicklaspoke** [comment]
Nope, it doesn't  occur with grass or any vanilla minecraft flower.
I can further add that this happened on FTB Infinity 1.8.2 with Botania updated to the lastest version.

**Comment by 0xc6** [comment]
@Nicklaspoke The Vajra is one of the most broken items that I have ever come across. As far as I can recall, it has a custom implementation for its Accurate (silk-touch) mode, which allows it to obtain blocks not normally available with silk touch (examples include End Portal Frames, etc.). Said implementation also causes it to interact with other modifications in unexpected ways (manifesting themselves in a variety of duplication bugs: warded blocks from Thaumcraft drop their item without being destroyed; Forge Microparts drop multiple items for each part; flowers from Botania drop more than one as is demonstrated here). I am fairly sure that this bug is the fault of GraviSuite.

I would complain about it to GraviSuite's author, SeNtiMeL, although judging by the frequency that he monitors the IC2 forums, you are unlikely to get a fix anytime soon.

On a side note: is this just generating flowers and the Pure Daisy which are duplicated, or all Botania flowers? If this is applicable to all flowers, I would suggest editing the title.
