### ISSUE TITLE
Client/Server Desync with Solegnolia

### ISSUE THREAD

**Issue by GauHelldragon** [Vazkii/Botania#1369]
When playing single player, I sometimes encounter a situation where a solegnolia has mana and the proper redstone signal, but my client seems to think it is deactivated. It does not have particle effects and items look like they are being attracted to me. However, on the server side it seems that the flower is behaving correctly. 

The result is items appearing to be pulled towards me, but never actually being picked up.

I am not sure what causes this issue to happen. It does not happen all the time but it does seem to happen fairly frequently in single player. It might possibly be triggered by chunks being unloaded/loaded or game being saved/loaded?

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
