### ISSUE TITLE
Daybloom will not connect to mana spreader

### ISSUE THREAD

**Issue by SinMattzor** [Vazkii/Botania#1370]
I placed down a mana spreader and guided the mana to a mana pool. Placed down multiple daybloom in a diagonal pattern. When clicking on the daybloom they all show a picture of the spreader with a "x" beside them. I am assuming this means they are not connecting. 

Server and mod stats:
FTB Infinity 1.10.1
Minecraft 1.7.10
Botania r107-208

Including a screenshot

http://puu.sh/k75X0/19e2e05bf9.jpg
![image](https://cloud.githubusercontent.com/assets/14227603/9805548/08243d4a-5808-11e5-8855-303a3a330d7e.png)

**Comment by OJwithC** [comment]
...Have you tried binding them manually with the wand in bind mode?

**Comment by SinMattzor** [comment]
Does it normally require it to be manually binded?

**Comment by Zsashas** [comment]
Normally, Dayblooms require manual binding. Not all flowers seem to require this, though. Endoflames for example, seem to bind automatically.

**Comment by eslachance** [comment]
Small hint in regard to binding: When you place a flower, it will bind to the closest spreader. So if you're playing your dayblooms *after* the spreader, you won't have this issue. Also, if you remove the spreader the binding is lost. However, I've noticed that the binding seems to be to a block space, not the spreader itself, so if you place it back (or upgrade it) the binding is restored automatically!

when you get a chance, make a Floral Obedience Stick. It'll bind any flower in the vicinity of a spreader when you shift+right+click on it. Because individually binding them can be such a PITA!
