### ISSUE TITLE
Idea: Livingwood Funnel

### ISSUE THREAD

**Issue by riskable** [Vazkii/Botania#1400]
Basic concept:  It works just like a hopper but it only has one inventory slot and only stores one item at a time and doesn't allow stacking.

When making crop farms and many other automated things with Botania we basically need one hopper for every Dispenser or Corporea Funnel.  This adds up to a *lot* of iron very quickly.  Another problem is that because the Runic Altar recipes often require multiple of a single ingredient (e.g. 3 Manasteel Ingots, 3 saplings, etc) using vanilla hoppers to deliver the items is risky since there's a chance that when a minecart (or other mechanism of dropping goods into hoppers) drops items it could drop more than one at a time (no matter how careful you are with timing it there's always a chance you'll get two instead of one).  With a single-item-only hopper-like mechanism you wouldn't have to worry about that problem because you could turn off the Livingwood Funnel with a Redstone signal and know that it will only ever have just one item inside.  Turn off the Redstone signal to drop the item--perfect!

It would also be nice if we could place an item frame on this Livingwood Funnel to "lock it" to only accept that item.  Much like how placing a Hopperhock next to a chest or vanilla hopper would have it placing only that item in the frame.  Alternatively, you could support that feature only using an upgraded version; a Dreamwood Funnel or similar.

Of course, it would also be nice if the Livingwood Funnel had Redstone Comparator support to allow for detecting when it is full (of it's single-item inventory).

I can think of loads of uses for something like a single-item hopper.  It would be useful for all sorts of things from being a cheaper alternative to hoppers to allowing finer control over how many items end up in being delivered to something like a Runic Altar.

The most difficult part of automating the Runic Altar is ensuring that the correct amount of each ingredient gets delivered.  You can pre-place your recipes by hand like I demonstrated in my video (https://youtu.be/bDtoajbSCh0) but if we had something like a hopper that only had a single item inventory it would be easy to make it so you could push a button to release just the right amount of items for any given recipe.

In my head I'm imagining a Hopper Minecart traveling back and forth over Livingwood Funnels that are locked to certain items as a means of efficiently and evenly distributing items into specific chests that belong to a Corporea network.  So you could have nice sorting along with the usual capabilities.  On one side of the rails you'd have a wall of blocks and the other side would have a Daffomill blowing items in their direction.  As the Hopper Minecart passes over the items it picks them up and as it travels back and forth over the Livingwood Funnels it will feed the items down into whatever inventories you like (e.g. chests).

**Comment by I-Need-A-Username** [comment]
Isn't the Corporea funnel already like this in a way? While it doesn't have an inventory of its own, it can pull a single item from any inventory connected from the network at a redstone signal.

**Comment by Reassembly** [comment]
I've wanted something like this for quite some time, for a few purposes. Many of my automated processing builds end up with extra item stacks uselessly sitting in the rightmost four hopper slots.if a hopper's output is any slower than its input. Also, the five-slot hopper throws FIFO right out the window if there's items of different types flowing through combined with any form of output slowdown.

One solution I've used for the first problem is to fill the rightmost four slots of a hopper with "filler" blocks, leaving only the first (leftmost) slot free to pass items through. This only works reliably if either the leftmost slot never empties (which would let the filler blocks fall out of the hopper next), or if the hopper empties into a block which refuses to take the filler blocks (e.g. furnaces won't accept dirt or smooth stone blocks, so they can be used to take up hopper space).

This suggests another approach to this issue. I don't know if Forge exposes enough events for this to be possible, but I'm imagining an item which can be moved between inventories by a player, but resists being moved by a hopper (or perhaps by any *automated* means, if that's possible and/or easier). Something made out of sticks, slimeballs, and *magic*, that would get "stuck" in a hopper, effectively closing that slot. Put in four, and you've turned a five-slot vanilla hopper into a one-slot vanilla hopper.

As I said, I don't know if such a "hopper plug" is possible, but if it is, I'd rather see a new item with potential uses *beyond* hoppers, rather than a new single-purpose type of hopper. If it isn't, then dreamwood hoppers would still be pretty cool.

**Comment by PsiGuy60** [comment]
@I-Need-A-Username Partially. The Corporea Funnel is both connected to a Corporea Network rather than a single inventory and it's always locked to a single type of item by virtue of needing an Item Frame placed on it to function.

This would basically have one inventory on top as its input, much like a vanilla Hopper, and one on the bottom/side. However, it'd not be necessarily locked to one item type. It'd also be pre-Corporea, and basically just a way to alleviate the ridiculously iron-heavy automation of Botania since most hoppers are already intended to work this way for Botania automation, and in fact the fact they don't always do so can cause glitches in builds (for example, Gourmaryllis builds can over-consume food if a hopper happens to pull 2 items instead of 1)
