### ISSUE TITLE
Massive lag with Munchdew.

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Vazkii/Botania#1414]
So I've got 1 ginnormous Sacred oak (BoP tree) growing, Munchdew munching on it, and felling. Problem is, as soon as my 5 Munchdew start munching on it, my FPS tanks to 10-12 fps max.

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
