### ISSUE TITLE
Terra Truncator doesn't handle big jungle trees properly

### ISSUE THREAD

**Issue by curiosity-a** [Vazkii/Botania#1460]
Grow a big jungle tree. Cut it down with the truncator. Observe some branches remaining.

**Comment by ray10k** [comment]
From personal observations, the Truncator seems to have trouble with diagonal connections in general. Case in point: for a certain build I needed large amounts of Greatwood Leaves from Thaumcraft. After shearing a tree bare, cutting down the bottom log of the trunk would only take down the trunk itself, leaving behind the branches since greatwood trees have branches with primarily diagonal connections.

**Comment by TheWhiteWolves** [comment]
The reason it doesn't deal with diagonals good is because it only searches on the directions contained in ForgeDirection.VALID_DIRECTIONS (which is DOWN, UP, NORTH, SOUTH, WEST, EAST).

The best way to get it to work is to leave the leaves on the tree as they are valid blocks in the search and can be used as a "connector" to the blocks that are diagonal.

**Comment by curiosity-a** [comment]
But it doesn't help with jungle trees, which may not have required leaves by default.
