### ISSUE TITLE
Redstone Mana Spreader does not unconditionally fire

### ISSUE THREAD

**Issue by DoomRater** [Vazkii/Botania#1462]
The Lexicon says that the Redstone Mana Spreader will in fact fire regardless of whether the mana beam has anywhere to go or not.  However, when testing it in creative I find that it sometimes doesn't fire under certain circumstances.  It fires most often when a Bore lens is attached, but placing an entropic lens does not cause it to fire unless it's pointed at a mana pool.  Sometimes when this lens is removed and a bore lens placed back on, it still refuses to fire.  I had been hoping to make a possible grenade launcher out of the redstone mana spreader for a castle defense.

**Comment by OJwithC** [comment]
You sure the burst expired before trying to send another one out?

**Comment by DoomRater** [comment]
I attempted this before the Redstone mana spreader had fired a single burst
to no effect.  Unless mana bursts continue through bedrock without
impedance even without a phantom lens, all bursts hit something and were
dissipated before I attempted to fire more.

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
