### ISSUE TITLE
Tooltip on Terra Shatterer

### ISSUE THREAD

**Issue by vengent** [Vazkii/Botania#1483]
When TS is in inventory, gradient is locked in place.  When it is placed in the hotbar, the gradient moves based on the mouseover.

Gif attached.
![terrashatterer](https://cloud.githubusercontent.com/assets/3430439/10729476/8c39beac-7bb7-11e5-966c-f53ff942e9c2.gif)

**Comment by Bellwar** [comment]
Oh goood again -_-

**Comment by vengent** [comment]
been identified before? I did try searching =(

**Comment by Bellwar** [comment]
I reported it but it was fixed i think. Maybe with the new change for manatablet it broke again.

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
