### ISSUE TITLE
Bug: Rod of plentiful mantle orbs are canceled when player enters bedrock fog

### ISSUE THREAD

**Issue by the-vindex** [Vazkii/Botania#1506]
As description says.
Botania 228

**Comment by howtonotwin** [comment]
Seems to be caused by the fact that bedrock generates thousands of particles. The orbs are being deleted as the game limits the particle count. Perhaps using the rod could remove the bedrock particles  or reduce their frequency on use, or just lore it away: "The pulsating energy of the Void below the bedrock layer interferes with the Rod's magic, consuming mana but showing only the slightest glimpse of nearby riches."
