### ISSUE TITLE
Shard of laputa stop

### ISSUE THREAD

**Issue by Akbalox** [Vazkii/Botania#1510]
Hello! I've admired your mod for minecraft since ever!
I've just found out that the shard of laputa stops working upon attempting to move one of my enhanced inventories chests, thanks for all your dedication, botania is beautifull! :)

**Comment by Akbalox** [comment]
well, I'm experimenting around it, i'll make a list of everything with this effect here
as said before, enhanced inventories chests do it
fells like bibliocraft armor stands do the trick as well, well, don't, just turned invisible, stopped once, I don't really know why

**Comment by mindforger** [comment]
take into account, that several other mods not beeing happy with their stuff moved around by other mods! i am pretty sure it is somewhere noted that you should not move advanced stuff around! just move a potion of ground and start THEN building your base upon it

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*

**Comment by Akbalox** [comment]
sorry, I just never contributed here, really, I just wanted to make contact to report the stuff, dunno, the shard of laputa is just beautifull, and it really moves most of the stuff up pretty well, I'd like to move my base up upon endgame, it's kinda bustballs to not being able to kkk, thanks for your dedication Vazkii Next time I'll be commenting like this just on the forums, Github is much more technical...
