### ISSUE TITLE
Bug: portal closes upon death

### ISSUE THREAD

**Issue by willky7** [Vazkii/Botania#1512]
Upon death my portal to alfheim closes. The pools are over half full, yet it requires me to reopen it every time upon death. I should note I have the chunk its in loaded with chicken chunks, but removing the chunkloader, reactivating the portal and dying again still deactivated the portal.
I have some other mods so I'll list them in this pastebin just in case:
http://pastebin.com/MubuSet5
(It's just the basic forge client so I don't have a log.)

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
