### ISSUE TITLE
Severe lag when opening lexicon in regrowth

### ISSUE THREAD

**Issue by baesianphoenix** [Vazkii/Botania#1547]
Just as the title, when I open my elven copy of lexicon after a few second i get severe lag, then I can't close windows or do anything but over the cursor arround. The game won't crash, but I can't close it becouse i can't open the option window at all. I have to shut it down forcefully. I have no crash report, so I don't know what to do. (I apologise for bad English)

**Comment by AlterAkima** [comment]
Does it happen on the latest Botania version?

**Comment by baesianphoenix** [comment]
It's the regrowth versionof botania, don't know if they are the same thing

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*

**Comment by thephoenixlodge** [comment]
@baesianphoenix The version in the current public release of Regrowth is build 230, which is one of the ones with this issue. I intend to release an updated version in the next couple days, but for now, if you're playing singleplayer you should manually update the mod.
