### ISSUE TITLE
Crystal Bow does not create arrows from mana in inventory in absence of physical arrows.

### ISSUE THREAD

**Issue by Braeghz** [Vazkii/Botania#1649]
I ran into this issue on an Infinity Evolved 2.1.3 server. Botania version 233. Putting arrows in my inventory allows the bow to fire normally. (this works as intended, by not consuming the arrows)

**Comment by JRoffel** [comment]
Please update botania to the most recent version (which is 242 right now) and try again, also try if you can reproduce the bug with just botania installed... A fml-log would be useful too

**Comment by acun1994** [comment]
To add, if the bow is enchanted with Infinity, it works as intended.

In Regrowth 0.8.6.

**Comment by Vazkii** [comment]
Can't reproduce, I can fire it just fine without arrows.

**Comment by Barhandar** [comment]
According to other places the bug is caused by [interaction of Botania and EnderCore](https://github.com/SleepyTrousers/EnderCore/issues/1) (specifically "infinibow" part of it). For some reason EC not only makes it so bows with Infinity can be fired without arrows, it also forces bows _without_ Infinity to require arrows, even when they have special mechanics.
