### ISSUE TITLE
Portal Visualization

### ISSUE THREAD

**Issue by Zsashas** [Vazkii/Botania#1662]
It says it requires Glimmering Livingwood in the material list, but the visualization and smaller image in the lexicon both show only normal livingwood. The only reason I even checked the material list is because I thought that it was weird that it no longer required glimmering livingwood.

![image](https://cloud.githubusercontent.com/assets/6917535/11819834/de17440c-a316-11e5-87ce-e62ff51cb774.png)

**Comment by yrsegal** [comment]
can you give us a picture of the visualization in-lexicon and in-world?

**Comment by Zsashas** [comment]
You should be able to see it behind the book. That isn't an actual portal.

**Comment by yrsegal** [comment]
Can you give us a clear picture, please?

**Comment by Zsashas** [comment]
![image](https://cloud.githubusercontent.com/assets/6917535/11839201/cd37979c-a3a0-11e5-8e31-0cf161426e87.png)
![2015-12-16_02 57 15](https://cloud.githubusercontent.com/assets/6917535/11839206/dc0e8db6-a3a0-11e5-9181-a2aa91be27a6.png)

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*

**Comment by Zsashas** [comment]
This is using the latest Botania.

Idk why it was closed...
