### ISSUE TITLE
Runic altar not consuming runes

### ISSUE THREAD

**Issue by eqdanteon** [Vazkii/Botania#1687]
I am not sure if this is the intended behavior or not but the runic altar is not currently consuming runes and returning both the new rune that is crafted as well as the component runes.  Running version 1.8-245.

**Comment by NezcalSpindrake** [comment]
Intended behavior.

**Comment by PsiGuy60** [comment]
Read the changelogs. Particularly for R1.8 238 - "Runes used for recipes in the Runic Altar are now given back upon the recipe's completion".

In other words, this is intended behavior - although I think it can't hurt to have a giant PSA about this, since this isn't the first "issue" we've had about the runic altar's new behaviour.

**Comment by Lazersmoke** [comment]
Wow I didn't notice this! This is awesome! Runes used to be a massive pain to craft

**Comment by Skar78** [comment]
Overlooked this change. So awesome. Thank you. (rune generation was a big turn off for me before)
