### ISSUE TITLE
A block is makeing the world to crash

### ISSUE THREAD

**Issue by lordweegee** [Vazkii/Botania#1701]
Hi I am playing the botania through the regrowth mod pack on FTB and Block18Stone is not rendering probably and is making the world crash when it is being loaded. Is there a way to delete this block from out side the game and the world in the code?

**Comment by JRoffel** [comment]
Look at crash report for coordinates -> download and open mcedit -> delete block at coordinates -> save and restart your world

This should temporarily fix your problem, however, to prevent other people running into this too, I would like to request you to upload your fml log, update botania to the latest version and test it again. This way we can fix the problem.

Thank you in advance,

J.Roffel

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
