### ISSUE TITLE
RenderPlayerAPIEnhancer

### ISSUE THREAD

**Issue by SvEgiiVEteR** [Vazkii/Botania#1716]
screenshot
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1283669-render-player-api?comment=501
vazkii.botania.client.model.armor.ModelArmorElementium
vazkii.botania.client.model.armor.ModelArmorManasteel
vazkii.botania.client.model.armor.ModelArmorManaweave
vazkii.botania.client.model.armor.ModelArmorTerrasteel

partially it works ... and partly not.
it can be fixed?
so it works .. but why 2 shows the old and new models.

**Comment by Lazersmoke** [comment]
Please read the contributing guidelines. I have no idea what you are trying to say

**Comment by TheWhiteWolves** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*

**Comment by SvEgiiVEteR** [comment]
screenshot all the necessary information available .. thank you for seeing ...

**Comment by Lazersmoke** [comment]
@SvEgiiVEteR if another mod messes up a vanilla class, then any bugs are on them.

**Comment by SvEgiiVEteR** [comment]
Many mode work with him Render Player API Enhancer
Thaumcraft-1.7.10-4.2.3.5.jar
BetterStorage-1.7.10-0.13.1.127.jar
and some others.
for this is the reason I decided to write, since your mod works too ... but in half, leaving the old location of your armor.
If you can fix, correct, but if not, then so be it :)
