### ISSUE TITLE
Bug that makes gaia guardian easy to kill. 

### ISSUE THREAD

**Issue by avis57** [Vazkii/Botania#1717]
If you back away from the gaia guardian after summoning and attack with only the beam from a terrasteel sword, the guardian just stands there and does nothing until it dies. 

Found in version r1.7-230

**Comment by JRoffel** [comment]
Please update to the most recent version of botania and forge, and try again. Also include a fml log of your session. After that we can take a look at your issue

**Comment by TheWhiteWolves** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
