### ISSUE TITLE
Possible issue or quirk of the Rod of Shifting Crust with snow layers

### ISSUE THREAD

**Issue by Kurbz** [Vazkii/Botania#1724]
When trying to replace blocks that have snow around and on top of them, the rod doesn't function. That is, with the 1 snow layers. Its likely not an issue at all, just a quirk of the behavior. A few pictures for clarification: http://imgur.com/a/peNmx

Botania version 1.8-243

**Comment by blacksmithgu** [comment]
This bug appears to show up for slabs and a few other blocks, as well, and is essentially because the Rod of Shifting Crust only tries to replace blocks which are visible (eg, not bordered by solid blocks on all sides). However, slabs and snow are considered "solid" blocks (due to having render type 0, which is valid according to `BlockCamo.isValidBlock`.

The easiest way to correct this is to instead check that each block being replaced should have at least one block with a non-solid side adjacent to it. Pull request forthcoming.
