### ISSUE TITLE
Pasture seeds will spread to dirt blocks underneath other blocks

### ISSUE THREAD

**Issue by NezcalSpindrake** [Vazkii/Botania#1728]
When using a seed, the initial spread will travel to dirt blocks covered by other blocks.

**Comment by blacksmithgu** [comment]
This is a pretty straightforward fix, and is because *BlockSwapper* in /common/item/ItemGrassSeeds.java doesn't check for a non-opaque block above the block it's swapping (see the *tick* method).

If anyone else who has some strong opinion would like to fix it specifically (or leave it unfixed), go ahead, or I will submit a pull request tommorow.

**Comment by yrsegal** [comment]
If this gets fixed here, guess i'm fixing it in BA ¯\_(ツ)_/¯

**Comment by blacksmithgu** [comment]
Where else does it need to be fixed? I can add that to the same pull request or to another one.

**Comment by yrsegal** [comment]
BA is my mod, I can fix it perfectly fine myself, thank you
