### ISSUE TITLE
Smokey Quartz is not interchangeable

### ISSUE THREAD

**Issue by Zsashas** [Vazkii/Botania#1758]
When disabled (because of Thaumic Tinkerer's version) the Flugel Tiara variant still requires Botania's Smokey Quartz, and will not accept alternates.

**Comment by TheWhiteWolves** [comment]
It because we declare the recipe for the variants in a loop instead of one at a time.

Due to the quartz types being added by us, I would guess it was never expected to need to oredict the recipe for them.

[https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/crafting/ModCraftingRecipes.java#L1410](https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/crafting/ModCraftingRecipes.java#L1410)

**Comment by Zsashas** [comment]
Well, the config option specifically says it's for those using Thaumic Tinkerer, so I assumed it would work with that.

**Comment by TheWhiteWolves** [comment]
yep it was, I'll take a look when I get home tonight
