### ISSUE TITLE
Corporea NEI request unable to handle localised names

### ISSUE THREAD

**Issue by netzgeist** [Vazkii/Botania#1764]
Setup:
Have latest Forge, Botania, NEI on a dedicated Server, connect as a client. Build a minimal corporea setup with Index. Succesfully request an item via NEI(c). Change your language to german and retry. It wont work. Change again to english and it will work again.

This issue is not present on SSP though

**Comment by netzgeist** [comment]
@TheWhiteWolves I don't want to complain but is this really #1605 to you? A player using localisations for several years is very bound to it. Reverting to english takes tremendously much away from my comfort, missspelling NEI searches etc all the time.

**Comment by TheWhiteWolves** [comment]
From the Labels I have available yes, the choice is either minor or gamebreaking, its not a gamebreaking bug so it gets a minor label, though i did foget to give it the bug label

**Comment by howtonotwin** [comment]
This bug is caused by the fact that the server will localize item names separately from the client, so the client might send `"1 bloque de diamante"` but when the server does `stack.getDisplayName()` it gets `"Block of Diamond"`. This causes Corporea to not work _anytime_ the server and client don't share a language. Perhaps, as a bandaid, instead of sending the localized name, add support to use unlocalized names? This will allow NEI requests to work, but will still make it difficult to do it manually.

**Comment by yrsegal** [comment]
another possible bandaid: packets.

**Comment by howtonotwin** [comment]
Have we officially removed the challenge against packets?

**Comment by netzgeist** [comment]
Naive question from me: Wouldnt it be simpler to build the proper request clientside and then just make it send what the server currently expects?

**Comment by yrsegal** [comment]
that's the packet solution.
