### ISSUE TITLE
[Bug] Can't make a daybloom

### ISSUE THREAD

**Issue by nifker** [Vazkii/Botania#1780]
https://www.dropbox.com/s/rd7pp4a1v6dpl44/2016-01-30%2014-35-04.mp4?dl=0

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*

**Comment by nifker** [comment]
So hard to answer why I'm not able to make a daybloom?

**Comment by nifker** [comment]
@Vazkii better purist?

**Comment by Vazkii** [comment]
Same thing.

**Comment by TheWhiteWolves** [comment]
You're missing tons of needed information, e.g. what mods are you running, can you reproduce with only botania installed, logs etc and thats only the start of things.

Try again and come back.

**Comment by AlterAkima** [comment]
It's human error, the petal used in the recipe is light blue, not cyan.
