### ISSUE TITLE
**CRASH** Ring of Magnetism + Hopper

### ISSUE THREAD

**Issue by ArkavianX** [Vazkii/Botania#1790]
There appears to be a crash when collecting items while standing on a vanilla hopper and having the ring of magnetism active.

**Comment by mindforger** [comment]
if there is a crash, then there is a crashlog too

**Comment by TheWhiteWolves** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*

**Comment by ArkavianX** [comment]
The modpack is ATL Skyfactory 2, as for crashlog, haven't seen one yet

**Comment by mindforger** [comment]
take the one with the reffering date and time, if you are not willing, you'll probably not get any help ... 
what do you think they owe you to do?

**Comment by JRoffel** [comment]
Follow mindforgers instruction for finding the log, open it in notepad or equivalent, and throw it into pastebin... Then give us the link... Not a lot of trouble to go trough, right?
