### ISSUE TITLE
[Suggestion] alternative Redstone Mode for Spark Tinkerer

### ISSUE THREAD

**Issue by 4Magma** [Vazkii/Botania#1824]
Current Mode is to switch the augments on redstone pulse.
An addional Mode should switch if signal is on or off.
Switch between modes through solo crafting or with
wrench like item (wand of forest, redstone torch ...)

example:
- pressure plate switches between dominant and dispersive augment

**Comment by PsiGuy60** [comment]
Okay, 2 things wrong here.

1. Suggestions posted via the issue tracker haven't been accepted in a *long* time. In fact, I think there was official policy about this somewhere.
2. Vazkii, the lead developer, quit working on this version to preserve her sanity. There are ongoing efforts by williewillus to port the mod to 1.8.9.

**Comment by williewillus** [comment]
Suggestions go on reddit

**Comment by TheWhiteWolves** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
