### ISSUE TITLE
Gaia Guardian is unbalanced

### ISSUE THREAD

**Issue by Vazkii** [Vazkii/Botania#1888]
It seems that as of the 1.9 combat changes (specifically the change to how Strength is applied), that the Gaia Guardian is insanely bullet spongey.

**Comment by williewillus** [comment]
For reference purposes, I made some minor changes in 1.9:

* If the GG teleports on a vector that intersects with a player's BB, it deals damage to them
* Magic missiles deal magic (durh) damage instead of physical
* GG can now be injured by projectiles, but still has the same hard-cap on damage. Did this because all my fights ended just being a very annoying (and blind and damaged) game of tag, which wasn't fun.

and yeah Strength got nerfed back to a reasonable linear buff instead of the ridiculous multiplicative insanity it was from 1.6-1.7
