### ISSUE TITLE
Bifrost Block not recognized by Chisel & bits.

### ISSUE THREAD

**Issue by CyaNox** [Vazkii/Botania#1892]
As mentioned in the changelog the bifrost block was supposedly made compatible with chisel and bits along with mana and elf glass. The mana and elf glass work as expected and are able to be chiseled however the bifrost block is not.

This may be due to the way it renders (the rainbow effect) but this is just speculation on my part.

Botania: 1.9-323
Chisel & Bits: 12.1

**Comment by yrsegal** [comment]
The rainbow shouldn't affect that, I think.

**Comment by TheWhiteWolves** [comment]
It won't be the rendering that's the problem, not quite sure on how C&B decides allowed blocks but its mostly likely because the Bifrost block has a TE associated with it and I suspect C&B doesn't allow TE's to be chiseled.

**Comment by williewillus** [comment]
^that's probably it. But the decor version of the bifrost shouldn't have a TE iirc

**Comment by TheWhiteWolves** [comment]
@williewillus You remember correctly it doesn't.
@CyaNox which version of the block did u try to chisel?

Would take a look at it in game but I'm at work so not able to :stuck_out_tongue:

**Comment by CyaNox** [comment]
@TheWhiteWolves "Bifrost Block" ... spawned in using JEI with the id: "botania:bifrostPerm".

This is also the only one I see in JEI that is called bifrost (not including the pane) and that isn't a temporary block.

**Comment by ParaDLell** [comment]
@CyaNox Chisels and Bits will not work with any block that emits light levels, and from the looks of it, Bifrost glass glows, and thus won't work.

**Comment by CyaNox** [comment]
@ParaDLell What about glowstone? Or even the light emitting variant of Flat Colored Blocks? Or even better ... Mana glass from botania itself? All of these emit light so your statement is incorrect.

**Comment by ParaDLell** [comment]
@CyaNox so it would seem I am wrong, however after a bit more testing I have found that animated textures doesn't effect C&B either as proven my the sea latern and the shimmer rock. However, soulsand, Jack o lanterns/pumpkins don't work, and redstone ore does work, but not when it's activated. I find it entirely plausible that it's because the bifrost glass emits sparkles [a special property] that it cannot be C&Bd. The only other block I could find with a special property that's still close to being a normal block is Slime Grass from Tinkers Construct [which lets you jump half a block higher] and this block also cannot be C&Bd. (The only outlier I could find is Slime Blocks, which can be C&Bd, but loose their bouncy ability)
