### ISSUE TITLE
Modern energy api

### ISSUE THREAD

**Issue by williewillus** [Vazkii/Botania#2117]
The fluxfield still uses RF, which is pretty much dead in 1.10+ (Tesla and Forge Energy are its successors). We should look at migrating it to one of those API's (I personally say FE because it's simple and no extra deps), or removing the fluxfield altogether

**Comment by TehStoneMan** [comment]
Please correct me if I am wrong, but the way I understand things, RF is an energy system, while FE is an energy compatibility layer.
Something along the lines of how Forge Fluids defines the common properties of fluids, but not the actual fluids themselves.

**Comment by williewillus** [comment]
FE is an actual energy system. Extremely basic but it's and actual one you can have units of

**Comment by tkdberger** [comment]
I say FE, since no extra dependencies.

**Comment by Bluexin** [comment]
Just my 2cents: Tesla is getting a lot of love from most big tech mods.
I've worked a bit with it myself, and have found it to be easy to use (also, it's a small dep :p)

**Comment by ArukaAlter** [comment]
Tesla allows for some power creep, wich Vazkii isn't a fan of, the fluxfield would have to get an exaggerated buff to fit in.

**Comment by tkdberger** [comment]
@Bluexin Deps are deps are deps are deps. FE already comes packaged in Forge without anything extra being installed by the user.

**Comment by Bluexin** [comment]
@tkdberger however one can easily make it an optional dependency, so that people that don't want integration with energy mods just don't need it (so no need to add anything on their end), while people that want said integration will need to add the Tesla jar (chances are high they already do if they use multiple energy mods anyway).

I do not know whether Tesla itself supports FE, however I can tell there's nothing related to FE in mekanism's (super messy) codebase.

As for @ArukaAlter I do not see why Tesla would "allow" power creep more than any other energy system though?

(please note that I'm not especially for or against one decision or the other, I personally prefer keeping my Botania setup "clean" from the energy pollution, for RP reasons. I'm just making sure the people that decide do so with the maximum amount of info)

**Comment by williewillus** [comment]
I don't want to add deps, so it's probably going to be FE

**Comment by tkdberger** [comment]
It's settled! 🎉
