### ISSUE TITLE
[1.10.2]Mana Prism with Messenger Lens bug

### ISSUE THREAD

**Issue by Myknakryu** [Vazkii/Botania#2121]
Minecraft version: 1.10.2
Forge version: 2202
Botania version: r1.9-339
Baubles version: 1.3.8
JEI version: 3.14.2.401

Mana Prism with Mana Lens - Messenger acts weirdly. Mana beam have very huge scale, which should not happen at all.

Video:
https://youtu.be/3amSfRnYENA

**Comment by Penrif** [comment]
Mana Prism is setting the starting mana of the burst to Messenger's much smaller amount, but this doesn't alter the burst's current mana.  Since scale is proportional to current mana / starting mana, it's being blown up rather large.

@Vazkii - would the proper resolution be to cap the burst's mana to the new starting mana value, or to cap the scale of rendering to 1.0f?  I'm happy to implement either.

**Comment by Penrif** [comment]
![image](https://cloud.githubusercontent.com/assets/17394578/23097647/994067a2-f5ed-11e6-8b66-e48b820d5fd0.png)
Alternatively, I went experimenting and have a setup where I'm capping the main burst to the new starting mana value, then taking the remaining mana and putting it in new bursts shot at random in a cone.  I think this has interesting potential uses.
