### ISSUE TITLE
Crash in Creative Mode, when switching to Botania Creative Tab. Caused by ItemEnderDagger

### ISSUE THREAD

**Issue by JaSpr** [Vazkii/Botania#2152]
When in creative mode, if I click the Botania Creative Tab, Minecraft *immediately* crashes. This happens for builds 339 as well as 340 (no other builds were tested). Both of the crash reports reference the ItemEnderDagger class at line 66.

[gist: Crash Reports for builds 339 and 340](https://gist.github.com/JaSpr/2736a5f60ab5f222acf09a22c107ebbc)

**Comment by JaSpr** [comment]
Did some research, and the NoSuchFieldError (from the crash reports) references field_185050_h, which is the Vanilla UUID for "Attack Speed Modifier".  It can be found in Item as Item.field_185050_h.

**Comment by williewillus** [comment]
does it happen on newer forge?

**Comment by JaSpr** [comment]
Just happened with Botania r1.9-341 on Forge 2.18.3.2189.  About to test latest forge.

**Comment by JaSpr** [comment]
Yes. This happens with Botania r1.9-341 on Forge 2.18.3.2544

[Latest crash report.](https://gist.github.com/JaSpr/6513cbf4b8326f11a6b4369a9e2596ee)

**Comment by williewillus** [comment]
Can you post your modlist? There's pretty much no way this should be happening 0.o

**Comment by williewillus** [comment]
Oh this is a dev/mcp environment, that might be why. Make sure your mappings are new enough

**Comment by williewillus** [comment]
shouldn't be a problem anymore in 1.12

**Comment by Frinn38** [comment]
I have a similary problem with minecraft 1.12.2, forge-14.23.1.2604 and botania r1.10-353

- I have set up an eclipse environment with this version of forge and the latest mapping.
- downloaded the latest version of botania and imported it as referenced library.

When I do it I can't launch minecraft from eclipse because it crash during the init phase with : 

java.lang.NoSuchFieldError: field_185050_h
at vazkii.botania.common.item.equipment.tool.ItemEnderDagger.getItemAttributeModifiers(ItemEnderDagger.java:66)

However I can compile it with gradle and launch it but it's a pain to have to compile my mod and test it in another minecraft every time I change a line of code.
