### ISSUE TITLE
Petal apothecary / Mystical Agriculture

### ISSUE THREAD

**Issue by LokyLive** [Vazkii/Botania#2271]
Hello i'm working in a new modpack for my community and i tryed to add recipe for Mystical agriculture to the Paetal Apothecary. The recipe appears well in JEI but MystAgri 's item won't enter in petal apothecary.

For exemple i used this 
mods.botania.Apothecary.addRecipe(<mysticalagriculture:tier2_crafting_seed>, [<ore:petalLime>, <mysticalagriculture:base_crafting_seed>]);

Version:
Botania r1.9-341
Mystical Agriculture [1.10.2]-1.5.4
Modtweaker 2-2.0.12
CraftTweaker -1.10.2-3.0.25
Minecraft 1.10.2
Forge 12.18.3.2297
Modpack : Growth 

PS: recipes works well in Runic Altar for Mystical agriculture
Edit: Same problem with other mods like actually additions or router reborn

**Comment by Hubry** [comment]
It's because the Petal Apothecary only accepts items implementing IFlowerComponent ([see here](https://github.com/Vazkii/Botania/blob/445ad284ec44f322f6b94a4ea06d1cc71c7301a2/src/main/java/vazkii/botania/common/block/tile/TileAltar.java#L127)) - from Botania it's just petals, runes, Gaia Spirits, Redstone Roots, Pixie Dust and Mana Powder. Make it a Runic Altar recipe, the altar doesn't have the restriction.

**Comment by williewillus** [comment]
^ (though that seems a bit limiting, maybe it can be changed in the future)
