### ISSUE TITLE
Marimorphosis flower crash fix doesn't work.

### ISSUE THREAD

**Issue by Riicochet** [Vazkii/Botania#2318]
I have read the same fix for this crash over and over but the fix won't work. I've changed the forge.cfg, Entity and TileEntity from false to true, saved and closed over and over but it never does anything. Ever. Please for the love of god help me.

**Comment by Hubry** [comment]
No console log, mod version info, Minecraft version info, not even a crash report? You're not helping us with helping you.

If you're on 1.10.2 - the fix was backported, but no build was released, and the Forge config option to remove crashing tile entities is kinda crashy itself (make sure to revert it to false). Use MCEdit to remove the crashing block - the crash report you definitely got (_and didn't post..._) definitely contains a part like this:
```
-- Block entity being ticked --
Details:
	Name: botania:specialflower // vazkii.botania.common.block.tile.TileSpecialFlower
	Block type: ID #239 (tile.specialFlower // vazkii.botania.common.block.BlockSpecialFlower)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (76,66,-21), Chunk: (at 12,4,11 in 4,-2; contains blocks 64,0,-32 to 79,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Actual block type: ID #239 (tile.specialFlower // vazkii.botania.common.block.BlockSpecialFlower)
	Actual block data value: 0 / 0x0 / 0b0000
```
Note the `Block location` part - use MCEdit to remove the block in that location.

**Comment by williewillus** [comment]
yeah sorry, we can't really update 1.10 now
1. try using the forge cfg option again
2. use mcedit
3. download and compile the latest 1.10.2 branch which has the fix but unreleased.
