### ISSUE TITLE
crash at loading

### ISSUE THREAD

**Issue by Hypsellis** [Vazkii/Botania#2380]
I started to get recently this crash https://pastebin.com/ffSLMYtY. I use Minecraft 1.12.1 and Forge 14.22.1.2480.

**Comment by b0bst3r** [comment]
More information on this, it's caused by autoreglib.

I just added skillable and autoreglib to my pack and get this crash.

Botania r1.10-347
AutoRegLib-1.3-13
Skillable-beta-7
forge-1.12.1-14.22.1.2478

**Comment by Vazkii** [comment]
I find it very unlikely ARL is causing this. It's more likely another mod
is packaging a bad copy of the botania API.

**Comment by b0bst3r** [comment]
Yep you're correct, trying to find out which right now

**Comment by b0bst3r** [comment]
Ok so the crash is caused by a combination of mods, in short 

Botania + Better with Mods + Immersive Engineering = crash

Botania + Better with Mods = no crash
Botania + Immersive = no crash

Immersive Engineering DOES ship Botania API
Better with Mods as far as I can tell does not ship any API (besides it's own).

For this test only I opened Immersive Engineering's Jar file and deleted the botania API and the crash went away.

Will log with IE.

**Comment by b0bst3r** [comment]
Sorry for blaming autoreglib I updated to latest IE at the same time as adding in Skillable + auto so it threw me a curveball.

**Comment by Hypsellis** [comment]
The problem is still not solved, the crash still occurs with the new version. https://pastebin.com/D2hE3P64

**Comment by williewillus** [comment]
this is a bug in IE, nothing botania can do.
