### ISSUE TITLE
Breaking red stringed container causes game to crash.

### ISSUE THREAD

**Issue by Branjoman** [Vazkii/Botania#2384]
I was messing around with red stringed containers (trying to get them to link to the central block of an IE Arc Furnace). I had placed at least a dozen of them around it trying to get it to work, but to no avail. When i tried to break one, the screen went a grey colour with some weird text in the centre, and then the game promptly crashed. This bug happens whether the red stringed containers are linked or not, but I am not sure if it affects other red stringed blocks - it also did not affect at least one of the red stringed containers I broke for an unknown reason.
Crash Log:
[https://pastebin.com/ub9b701F](url)

**Comment by quat1024** [comment]
I can reproduce this with all red string blocks (not just the red string container), and with just Botania~~and itemscroller~~. Crash log is the same as yours: https://paste.ee/p/gYyZc

I tend to crash slightly less often when I remove a red string block that is bound to something but it's not consistent.

Btw, i believe the "weird text" you mention is the game trying and failing to draw a "Shutting down internal server..." message. Possibly due to the GL state being all wacky, because the crash *is* in the middle of the red string spiral effect rendering method.

**Comment by codycoolwaffle** [comment]
Was running this with only Botania on 1.12, could not duplicate.
