### ISSUE TITLE
Soujourner's Sash Step feature does not work when stepping from farmland directly onto a higher block.

### ISSUE THREAD

**Issue by Scorch-Mechanic** [Vazkii/Botania#2392]
Build 347 for minecraft version 1.12.1. Full modlist attached. Autojump is disabled.

[soujourner sash step modlist.txt](https://github.com/Vazkii/Botania/files/1330306/soujourner.sash.step.modlist.txt)

**Comment by TheWhiteWolves** [comment]
Isn't farmland 1/8th or 1/16th of a block lower than normal? (been awhile since I looked)

iirc the belt only sets the step height to 1 so if its a slight bit lower, e.g. snow, possible soul sand and possible farmland then it won't be able to make that step up due to it being a height greater that 1.0

**Comment by codycoolwaffle** [comment]
This is more a question of if Vazkii wants it to be 1 block and that's it, or extend it for these special blocks.

**Comment by Vazkii** [comment]
This is intended.
