### ISSUE TITLE
Tree Farm pre-alfheim issues

### ISSUE THREAD

**Issue by Satrman** [Vazkii/Botania#2411]
So here's a list of current problems:

My Hopperhocks aren't responding to redstone timers.
The Hopperhock on the left is the only one picking up anything, the one on the right picks up nothing(aside from a rare piece of birch wood but even this is few and far between compared to the set-up on the left side) despite both being attatched to a mana pool and properly set up.
My Rannuncarpus both do not pick up nor plant saplings dropped by open crates as the Hopperhock collects them too quickly.
Using Floating hopperhocks/grounded rannuncarpus' does not change any of these problems.
![image](https://user-images.githubusercontent.com/32682998/31523472-c730b4e8-af81-11e7-8122-edff1e6d4975.png)

**Comment by codycoolwaffle** [comment]
Gonna need some more info here.


Your hopperhock appears to be attached to a pulse-timer, meaning after a set amount of time, it sends ONLY a pulse. Hopperhocks get disabled from a redstone signal, so it's being disabled for only a moment. Was this intentional?

Your rannuncarpus should be able to place before the hopperhock can pick it up, so the rannuncarpus is likely not setup properly.

This seems more like a user mistake, and not a bug, so unless you can show something is wrong with the mod itself, this should be posted on a forum. Not the issue tracker.

**Comment by Satrman** [comment]
Well, I would have been poting this anywhere else if anywhere else had an inkling of being helpful.

Anyways, The redstone to the hopperhocks was intended to make it only go off every minute, giving time for the rannuncarpus' to place the saplings coming from open crates. I wasn't aware it had to have an ACTIVE redstone signal to be off, since y'know, redstone being on implies whatever it connects to is ACTIVE.

I've resolved some of the issues, such as: Rannuncarpus' were on top of a grass block while the line i had for the sapling was dirt specifically, which they seem to be super picky about, matching those helped.

The Rannuncarpus' have the problem now of placing tree blocks on occassion, but otherwise the issue is resolved, thanks for the help.
