### ISSUE TITLE
Lag from Sparks

### ISSUE THREAD

**Issue by ResqDiver1317** [Vazkii/Botania#2428]
We have a custom built modpack on MC 1.10.2 running Botania R1.9-341. We had a player tonight setup his mana system and had 10 pools with sparks equipped with recessive augments on them to feed up to 6 pools above. This setup was bring our TPS down to around 3, and TickProfiler was showing his chunk and the sparks as using 71% of the server. He removed the sparks and everything went back to normal. 

Is there a way that I can reduce the load the sparks are causing or is this possibly a bug that can be addressed?

**Comment by williewillus** [comment]
1.10 is no longer being updated but I'm still interested because the spark code hasn't changed since then and it could still be a problem now.

Can you link any profiler reports you made with TickProfiler/vanilla profiler/Sampler/WarmRoast/etc.?

**Comment by ResqDiver1317** [comment]
I had to edit the settings for the TickProfiler (it was set to not record the data to a file). After our next restart, I will run a report and post the results. 

I did get a couple screeshots of the offending setup and of the in game report it gave. I know it won't be very helpful, but figured it was a start until I get the actual profile report saved/posted.

[![Screenshot from Gyazo](https://gyazo.com/11e5e48592ca1028eca435c15a46eee4/raw)](https://gyazo.com/11e5e48592ca1028eca435c15a46eee4)

![2017-11-02_13 40 04](https://user-images.githubusercontent.com/18246580/32344036-7349969e-bfd3-11e7-8cb9-3d68e836262d.png)
![2017-11-02_13 40 11](https://user-images.githubusercontent.com/18246580/32344037-735ac766-bfd3-11e7-8c15-af6f34c8e20b.png)

**Comment by ResqDiver1317** [comment]
[profile.txt](https://github.com/Vazkii/Botania/files/1442887/profile.txt)

**Comment by williewillus** [comment]
Can you use a JVM profiler like visualvm or warmroast so it can show where exactly in the spark code it happens?

**Comment by ResqDiver1317** [comment]
Sorry for the delayed response, got busy sorting other issues and stuff IRL. Unfortunately, the one admin who has enough access to the server to use something like warmroast is not currently active. My access to the actual server is limited to what I can access via our multicraft panel and FTP into the directories for the MC server folders as provided by the multicraft FTP Control meaning I can't install and run something like warmroast. 

The only profiles/timings I have found that I can do is TickProfiler which pretty much only seems to give me the same info it shows in game (screenshot above) or the Sponge Timings.

**Comment by HeberonYT** [comment]
I have the same problem, please optimize the spark code, they are causing my server to drop to 6tps when a user puts several of them.
I am using the Modpack FTB Beyond 1.10.2

**Comment by williewillus** [comment]
I can't do anything if you don't give me profiler reports

The latest 1.12.2 build also has a patch that should result in a lot less network traffic when sparks/pools are idle, perhaps that will help

**Comment by HeberonYT** [comment]
Friend, I do not have free time to install any profiler on my dedicated server, just as the first user has complied with tracking and reporting the problem, if you want to fix it; Great, otherwise it will continue to affect other users, if you need to know the exact line of code that should change, then make your own tests, and "meet your own requirements". 
Just install the mod and place sparks in the world and you will notice the bad performance.

If you say not to support version 1.10.2, which hurts, the biggest modded networks are in 1.7.10 - 1.11.2, I do not know who will benefit from solving this type of problems in version 1.12, probably only to singleplayer games.

**Comment by Goof245** [comment]
Maybe this isn't a problem in willie's current configuration? Perhaps post a world save in which you can demonstrate this "bad performance", and then someone else might be kind enough to profile the world for you. Or are you _waaaaay_ too busy to even bother with that?

There's a reason willie keeps asking for warmroast reports instead of tickprofiler reports. Tickprofiler only tells you _what_ entities are lagging. Warmroast tells you _why_ they are lagging.

**Comment by Darinth** [comment]
And the why is important, because entities perform actions that often end up calling code from other mods indirectly. It may well be that the sparks are perfectly fine, but another mod is causing lag through an indirect call in their code. I have a FTB Beyond server with dozens of sparks and no issues with them. (There are other issues, but I already know those are addressed in the current 1.12 branch, so I'll have to be sad while I wait for some of the other mods I really want to be updated. <3)
