### ISSUE TITLE
Is This Crash the Same as #2380?

### ISSUE THREAD

**Issue by InterPlay02** [Vazkii/Botania#2461]
**Forge version:** forge-1.12.2-14.23.1.2562
**Botania version:** Botania r1.10-350
**Link to crash log:** https://pastebin.com/g0JQsJdd
**Steps to reproduce:**
1. Just clicked the green Play Button on the Launcher.
2. The forge loading screen starts loading.
3. While in the Pre-inicialization phase 1 or 2......
**What I expected to happen:**
The game should load corectly!
**What happened instead:**
But crashed before the main menun shows up.

**Additional information:**
I have these Java Arguments in the Launcher:
`-Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M`

**Comment by FloressaX** [comment]
Hi, I was getting this crash too so I did a remove all mods and add them back in one by one. Turns out it doesn't crash when I remove Chisel. Chisel & Bits is fine just Chisel seems to be causing this crash for me. Have you tried removing just Chisel? Let me know if this works for you too. Might have to report to Chisel.

**Comment by InterPlay02** [comment]
Yes, it was Chisel. But not because of Chisel itself. Its just because I don't dowwnloaded the new api needed by Chisel for it  to work proprely. It is called CTM (Conected Texture Mod).
