### ISSUE TITLE
Botania Flower

### ISSUE THREAD

**Issue by blOgre** [Vazkii/Botania#2508]
Modpack version: All the Mods 3 v 5.6
Minecraft version: 1.12.2
Forge version: 14.23.1.2568
Botania version: 1.10-353
Magic Bees verson: 1.12-3.1.7
Gendustry version: 1.6.5.6
Link to crash log: No crash

Steps to reproduce:
1. Have bees with botania flowers in gendustry apiary spread flowers.

What I expected to happen: Botania Flowers spawn from bee pollination. 

What happened instead: Produced `Miscellaneous Flower` got achievement for picking the magenta and black checkered cube. (Says to report it so I am)

Not sure if you guys collaborate or if I should post this on other places as well, maybe tags not getting set on flower generation from hives.

Other botania/bee flowers are checkered boxes as well `Beegonia`  `hiveacynth` from magic bees.

**Comment by wrincewind** [comment]
I got the same thing - though mine was using a Forestry Apiary with Somnolent bees in it.I do have Gendustry installed, but i'm pretty sure it's Magic Bees at fault  - particularly because it lists the offending genome as 'magicbees.alelle.flowersbotania' instead of 'Flowers: Botania' as it does for other types (e.g. 'Flowers: Cacti')

I'm running a tweaked version of the Direwolf20 pack.  My log (Which should show all versions of everything) is at https://paste.ee/p/wD1gv
