### ISSUE TITLE
Suggestion: JEI support for Orechid(ignem)

### ISSUE THREAD

**Issue by Thyriel** [Vazkii/Botania#2549]
Just a suggestion that would greatly help in heavily modtweaker altered orechid/ignem modpacks: Would be great if JEI would show what kind of ores/blocks the orechid and ignem can generate (maybe even with a %chance or so)

**Comment by Saklad5** [comment]
You aren’t supposed to post suggestions here. Close this and ask on Reddit or the forums.

**Comment by TheWhiteWolves** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
