### ISSUE TITLE
Baubles disepearing

### ISSUE THREAD

**Issue by multibeasty** [Vazkii/Botania#2590]
# Version Information

Modpack: Modern skyblock 3.2.0.1
Forge version:  
Botania version:  

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
1. Have 2 of the same bauble
2. hold right click
3. watch it poof

What I expected to happen:
infinite swapping

What happened instead:
poof

Additional information:
changing the name or any littlest bit in the items data fixes it (ie mana band getting 1 charge)

**Comment by williewillus** [comment]
Full info for forge ticket:

1. bauble A loaded into baubles inv
2. bauble B, equivalent in all manner to bauble A, right clicked
3. this is supposed to exchange bauble A and B. The held item is set to A, and handler.set(B) is called.
4. However, handler.set silently discards B, leaving A in both the player's hand and baubles inv
5. You've lost bauble B not since both stacks are the same identity object, a subsequent shrink poofs both
