### ISSUE TITLE
Rannanacarpus wont place dropped saplings

### ISSUE THREAD

**Issue by FSFan** [Vazkii/Botania#2695]
I have set up an automatic tree farm that is a cross between DrRageHard's (rageplaysgames) and Vallen's (mischief of mice) tutorials.  I have my Rannanacarpus set up to plant birch saplings.  Saplings that fall from t he trees after harvesting and saplings that I've get set up to come out of an open crate will not get planted by the Rannanacarpus.  If I throw the saplings out manually from my inventory, they will get planted.

**Comment by FSFan** [comment]
Oops!  Guess I should have said I'm using MC 1.12.2.  Sorry

**Comment by williewillus** [comment]
can't reproduce, make sure nothing else is eating the sapling, and that your open crate doesn't have a redstone signal on it accidentally (which will make the rannuncarpus wait 10 more seconds than usual)

**Comment by ElectronicRU** [comment]
I've had a rather annoying issue with my Rannuncarpus/Hopperhock setup, with Hopperhock floating/Mycelium, about 10% of the time it would still get ahead on Rannuncarpus and snatch the sapling before it could be planted. With Podzol instead of Mycelium, it happened about 50% of the time. Maybe this is related.
