### ISSUE TITLE
Entities and some blocks (TESRs?) not rendering through sparks and the Alfheim portal block.

### ISSUE THREAD

**Issue by LumberWizard** [Vazkii/Botania#2736]
# Version Information
Forge version:  14.23.4.2751
Botania version:  r1.10-356

# Further Information
Steps to reproduce:
1. Place a spark on top of a mana pool/open the portal to Alfheim.
2. Try to look at an entity or TESR through the semi transparent parts of the spark/portal.

What I expected to happen:  
The entity/TESR would be visible through the spark/portal.

What happened instead:  
The entity/TESR was invisible, and I was able to see the block(s) behind them instead.

**Comment by codewarrior0** [comment]
This is a general Minecraft issue that affects any TESRs that render with transparency. 

Blocks with transparent visuals are sorted from furthest to nearest before being drawn, so that the near ones don't mask out the far ones. This is not done for TESRs. 

If there's a solution on Botania's side, it's to move the transparent visuals out of the TESRs and into the block rendering.

**Comment by williewillus** [comment]
Still valid, but probably unfixable until 1.15

**Comment by williewillus** [comment]
this is as fixed it can get in 1.15, it's better but there's still some oddities but not much more can be done on our side
