### ISSUE TITLE
Phantom+Messenger lens bursts go through hovering hourglasses without signalling them to start/stop.

### ISSUE THREAD

**Issue by VoilaTada** [Vazkii/Botania#2737]
# Version Information
Forge version:  14.23.4.2760
Botania version:  r1.10-356

# Further Information
Link to crash log: No crash
Steps to reproduce:
1. Make a compound lens using phantom and messenger lenses. 
2. Place the compound lens on redstone mana spreader and aim at hovering hourglass with sand in it.
3. Supply mana and activate redstone mana spreader with redstone signal.
4. Be surprised when the burst travels through the hourglass without making it stop/start.

What I expected to happen: I expected the burst to affect the hourglass in the same way all other bursts do.

What happened instead: The hourglass ignored the burst despite them making direct contact and it being a block that accepts a burst for a function.

**Comment by codewarrior0** [comment]
Are you sure the hourglass actually ignores the burst?

I've used that same lens to trigger a Drum of the Canopy multiple times with a single burst, so maybe it's just rapidly toggling the Hourglass and leaving it in the same on/off state it started in.

**Comment by williewillus** [comment]
^, you can see the effect by using mana powder in the hourglass instead

**Comment by VoilaTada** [comment]
I know this is a late reply but, even if it does as you say, that's still unexpected behavior and could count as a bug. Players would expect a messenger lens to supply that mana burst 'message' and the fact that the hourglass did not turn on/off after being hit with the burst implies to the player that the message was not received. It's not intuitive behavior for the hourglass to toggle rapidly as that is never useful with that particular device. Additionally, I would actually go so far as to report the rapid Drum of the Canopy activation with a single burst a bug as well, even if that's what you wanted out of it.

**Comment by codewarrior0** [comment]
It's more nuanced than that. You see, the Hourglass will toggle on and off for each tick that the Phantom burst spends traveling through it. If you had fired a burst through the Hourglass at a different angle, the burst might have turned the Hourglass on or off due to having spent an odd number of ticks traveling through it, and you would not have found any issue to report.

**Comment by williewillus** [comment]
yeah, I'm not sure whether this should be a bug or not, especially since a lot of things in botania detect on world tick granularity when it should actually be aligned with redstone ticks (e.g. the mana detector pulses faster than anything else in vanilla redstone if you fire a fast burst through it)

**Comment by VoilaTada** [comment]
I addressed all of that in my reply. The fact of the matter is that it's not expected behavior. Unexpected behavior can be reported as a bug. This is the case for all game related bug reporting. Whether or not it will be fixed is still up to the developer. Maybe there's a good reason for it not to be changed. I don't know the details in the code. All I know is that unexpected behavior occurred and that I feel the developer should be made to know of that behavior. It doesn't have to do with whether or not I described the bug in exact detail down to the line of code responsible for it or not, as long as I provide enough information that it can be reproduced or investigated at some point. That being said, describing the nuance of the situation will undoubtedly help a developer narrow in on the bug and help decide if it needs changing or not, so thank you for pointing out how it is reacting to the phantom lens and world ticks.

**Comment by codewarrior0** [comment]
I expected the Phantom Burst to trigger multiple times as it passes through a block, so saying it is "unexpected behavior" is certainly debatable.

**Comment by codewarrior0** [comment]
Of course I had to do an experiment. Reading the Lexica and experimenting with ordinary mana bursts led me to expect one of four possible outcomes for the Phantom burst striking the drum: 

- The drum would consume the Phantom burst, ignoring the lens effect (since otherwise the drum could be triggered for no mana cost)
- The drum would trigger once as the burst initially strikes it
- The drum would trigger multiple times as the burst passes through it
- The drum would not trigger at all (in the case that it triggers when the mana burst collides with it, and the Phantom effect prevents the burst from colliding). 

The text of the Lexica does not favor any particular outcome; in fact, it doesn't even state that a burst has to collide with the drum in order to trigger a beat! Merely that a burst is fired in its direction.

**Comment by VoilaTada** [comment]
That sure is a list of all the possible outcomes. However it doesn't change the fact that if we replace the drum in that with the hourglass, the only reasonable expected outcomes are that it is activated once, therefore toggling its activity, or that it either ignores the lens or the block. The hourglass is toggled by a burst. not activated like a drum. It would be unreasonable for it to be toggled repeatedly by a burst because a burst is described in the Lexica as a means to toggle it. If I had a series of hourglasses and wanted to toggle all of them with a single burst, I would use the phantom lens in an attempt to do so, and the expected behavior would be that all the hourglasses would toggle when the burst went through each one. Instead there would be inconsistencies because of the world ticks that it takes for the burst to go through each hourglass and their position relative to the spreader. This is unexpected behavior from the perspective of a user interacting with mana bursts and the hourglass. The drum is inherently different from this situation because the drum is not toggled so the same expectations are not applicable.

**Comment by codewarrior0** [comment]
Frankly, I'm afraid that the resolution to this issue will be to change all mana-activated blocks, including Hourglasses, Drums, and Animated Torches, such that they will consume any mana bursts that activate them.
