### ISSUE TITLE
Spectrolus Balance

### ISSUE THREAD

**Issue by Karthas077** [Vazkii/Botania#2775]
# Version Information
Forge version:  14.23.4.2766
Botania version:  r1.10-356

# Further Information
Spectrolus currently has zero tick delay on how frequently it can consume wool. Before I started using Botania I wouldn't have considered this a problem, but then I decided to actually automate one with Integrated Dynamics...
Steps to reproduce:
1. Set up a counter with integrated dynamics that increments once per tick.
2. Trigger a different dropper modulo the counter (I used precision but I suspect it would work just as well with a vanilla one)
3. Spectrolus eats one wool per tick, overpowering everything except a Potency+Velocity Gaia spreader, and fully filling a Fabulous pool (plus the spreader and the flower) in approximately 2 minutes 50 seconds.

As a note: the automation was not very complicated or resource intensive using only sixteen precision droppers and sixteen redstone writers, but I will not be publicly sharing the details at this time. (Most of the fun was in figuring out how to do it)

What I expected to happen:
A nicely automated Spectrolus would, by nature of it's complexity perform a bit better than the simpler generating flora.

What happened instead:
A single Spectrolus outperforms entire fields of the other generating flora and the setup fits within a 5x5x3 space.

**Comment by Hubry** [comment]
I don't really think this is a big issue - the main problem is that you need about a double chest of wool for a single pool. Your mana production will far outpace your potential wool production. Also, when it comes to complex automation, using Integrated Dynamics is one of the best options over anything else, try to reproduce a setup like this without it :P

**Comment by Karthas077** [comment]
Putting aside the fact that functionally infinite wool is not a very high barrier, my stated concern is about the maximum mana throughput of the flower in comparison to the others. Three times faster than the next fastest flower (an Entropinnyum can handle a bit over 2000/sec) is enough of a gap to be noticeable, and even sticking a two tick cooldown on it would bring it more in line with the others.

**Comment by quat1024** [comment]
Well oops we just buffed the shit out of it, lol.

>Putting aside the fact that functionally infinite wool is not a very high barrier

IMO it is kinda difficult to do, which is a big part of why I chose to buff it. You need to either auto-spawn and kill spiders for string, craft, obtain all 16dyes, and dye it all 16 colors evenly. Or just make a sheep farm but you will need a lot of sheep.

Maybe other mods make that process more trivial (especially ID which is very good at making a lot of logistical problems very easy). But I don't think balancing around other mods is that big of a deal (I mean apparently Chickens has a cake chicken, no need to nerf the keki for that)

I agree that a cooldown or a "burn time" would be a welcome addition though. Especially since I think you can even dispense multiple wool in the same tick if you properly manage update order
