### ISSUE TITLE
Brewery destroys invalid brew containers

### ISSUE THREAD

**Issue by curiosity-a** [Vazkii/Botania#2803]
# Version Information
Forge version:  14.23.4.2766
Botania version:  1.10-356 **but!** I don't see it in the changelog and do see it in the code.

# Further Information
Steps to reproduce:
1. Place a tainted blood pendant or an incense stick into the brewery. Encountered with a pendant.
2. Put in ingredients for a brew that the container of your choice can't accept. Encountered with warp ward from Thaumcraft.
3. Point a spreader with mana on the brewery.

What I expected to happen:

Nothing.

What happened instead:

Brewing started as normal. When it finished, all items were consumed/destroyed (including the pendant).

**Comment by Hubry** [comment]
https://github.com/Vazkii/Botania/blob/e26e11fabb233fed9df0949767166a98afc98c53/src/main/java/vazkii/botania/common/block/tile/TileBrewery.java#L77

Well, this is a null ItemStack check... which means this is caused by a 1.10 port artifact, because these are supposed to be replaced by empty stack checks now.
