### ISSUE TITLE
[1.12] Lexica Botania pulling up wrong FTBwiki page

### ISSUE THREAD

**Issue by Vampyricon** [Vazkii/Botania#3020]
# Version Information
Forge version:  14.23.5.2847
Botania version:  r1.10-362

# Further Information
Link to crash log: N/A
Steps to reproduce:
1. Have Construct's Armory installed
2. Shift-use Lexica Botania on Armor Forge

What I expected to happen: FTBwiki for Construct's Armory Armor Forge to open

What happened instead: FTBwiki for ArmorPlus Armor Forge opened.

Not sure if this is a problem on FTBwiki's end, but I thought I'd bring this up here.

**Comment by Hubry** [comment]
The intended behavior is opening the wiki page named after the block you targetted. In this case, the page named after the block is not for Construct's Armory, but for ArmorPlus, because, well, no one decided to document Construct's Armory. I personally would expect this result.

This isn't really a problem on any end. Sadly, wiki pages aren't magic and don't coalesce from nothing (I say this from experience writing wiki pages for this very mod on the mentioned wiki), and the mod doesn't check if it exists and matches the mod (it would be much more complex than just opening the page). 

On a sidenote, this feature is getting dropped in the 1.14 port, as the lexicon is being moved to Patchouli.

**Comment by williewillus** [comment]
^ it just sends the block name to FTBWiki and anything after that depends on the wiki's pages. And yeah the feature is going away in 1.14 (at least for now)
