### ISSUE TITLE
Mass production with the Mana Pool slows down after a few items.

### ISSUE THREAD

**Issue by DasGerippe** [Vazkii/Botania#3120]
# Version Information
Forge version:  28.1.109
Botania version:  1.11-373

# Further Information
Steps to reproduce:
1. Set up a mana pool with enough mana.
2. Throw a stack of an item into the pool that can be infused with mana (f.e. iron ingots).
3. Watch how the items get infused really fast at the beginning (as in 1.12) but slows down after about 10 items.

What I expected to happen:
The speed at which items get infussed with mana keeps the same.

What happened instead:
The speed drastically lowered after about 10 items.

![MassProductionManaPool](https://user-images.githubusercontent.com/33161021/71783204-90b3b700-2fe3-11ea-8834-933bd4908bcc.gif)

The gif got a bit slo-mo on export...

**Comment by Z0rdak** [comment]
Can confirm this behaviour.

Version Information:
Forge version: 28.1.99
Botania version: 1.11-373

**Comment by tiggerbiggo** [comment]
I can also confirm, although idk if this is intended behaviour or not.

**Comment by Hubry** [comment]
Looks like... Mojang made item entities only do collision checking every 4 ticks if they are not moving. So if the item is not moving, it gets slowed down to 5 conversions per second. I get their reasons, but it's inconvenient for us :V

**Comment by tiggerbiggo** [comment]
As a workaround for @DasGerippe if you really need to enchant tons of stuff and this is an issue, 4 dispensers facing into a mana pool pulsing at max speed is a way of enchanting these items faster. Only worth it if you need to infuse tons of items but it does allow you to make them faster than chucking entire stacks in at once, since each item is an individual entity and is not stacked, so the standing still rule does not apply.
