### ISSUE TITLE
Open crate collision check could be more granular

### ISSUE THREAD

**Issue by jmhossler** [Vazkii/Botania#3212]
# Version Information
Forge version:  1.15.2-31.1.18
Botania version:  r1.11-379 & r1.11-378

# Further Information
Steps to reproduce:
https://www.youtube.com/watch?v=9MlUY10--N4

If I move the apothecary one block down, it works but reduces compactness.

What I expected to happen:
open crate to accept the filled bucket and refill the apothecary

What happened instead:
filled water bucket stays in the hopper, open crate doesn't accept it. It looks like there has to be at least 1 full block between the apothecary and the open crate.

**Comment by williewillus** [comment]
basically the problem is it checks "is there a block here" instead of "would an item entity fit here"

**Comment by williewillus** [comment]
Fixed the problem described above (the open crate will now check if the item will fit where it spawns it instead of just checking for a collision box anywhere in the blockspace

However, that wouldn't resolve your original issue, because the apothecary's collision box extends above its blockspace.

For super compactness you probably want a dropper facing sideways into the apothecary, since the apothecary does collision checks on all sides of itself, not just the top.
