### ISSUE TITLE
mc 1.15.2 , void while watching runic alter craft (valhesia 2 latest modpack version)

### ISSUE THREAD

**Issue by aknethia** [Vazkii/Botania#3237]
forge : 31.1.36
botania: r1.15-382
Is occurring in forge multiplayer server i have going. I have not tested in single player to see if this exists there as well.

looking with a wand of the forest or anything while runic alter is crafting, the world becomes nothing but void visually. but when watching it after going into the f1 mode, everything thing is normal , and when looking at anything else besides the alter while it crafts no issues.

![2020-04-08_00 24 49](https://user-images.githubusercontent.com/63335916/78751485-f5aae000-7937-11ea-85be-cde2eaf36b93.png)
![2020-04-08_00 24 55](https://user-images.githubusercontent.com/63335916/78751487-f6dc0d00-7937-11ea-9b96-91bc4b7f16a5.png)

**Comment by ridjack** [comment]
My wife and I are both also seeing this on a custom modpack server. Looking at the Runic Altar while it's crafting results in nearly everything except GUI elements disappearing.

Can provide logs, additional info or test whatever's needed on request; just let me know.

**Comment by williewillus** [comment]
this is always only when it's crafting? you've never seen it happen when the altar is idle?

**Comment by ridjack** [comment]
Correct.

**Comment by aknethia** [comment]
yup only when crafting

**Comment by elowanut** [comment]
Just wanted to chime in on this. I see a similar void, where terrain and objects are blanked out, but you can see water, including underground and through terrain.

In my case, this seems to be due to an incompatibility with the mod "Immersive Portals" ([here](https://www.curseforge.com/minecraft/mc-mods/immersive-portals-for-forge).) 

With Forge, Curios, Patchouli, Botania, Immersive Portals, and MixinBootstrap (required by Immersive Portals) installed, you get a weird blanking out effect _while crafting only, and while looking at the altar only_. 

Note that it starts as soon as the final item is added to the altar, and ends only after you place the livingrock, and use the wand. The effect only appears when you're actively mousing over the runic altar. It doesn't happen when not actively crafting. Removing Immersive Portals (but not Mixinbootstrap) stops it from happening.

For reference, I get this issue with (minimally) the following versions / mods:

**Forge**: forge-1.15.2-31.1.46
**Botania:** Botania+r1.15-382, curios-FORGE-1.15.2-2.0.2.1, Patchouli-1.15.2-1.2-31
**Other mods:** immersive-portals-0.12(forMc1.15withForge), MixinBootstrap-1.0.2

**Comment by bunnyman14** [comment]
I thought it might be immersive portals. Seems removing the portal wasn't enough.
I'll see if removing it from my modpack is viable; the last time I tried removing it my game crashed every time I loaded the world.

**Comment by tobi1449** [comment]
The issue is still occuring, any chance this might get fixed?

**Comment by hjake123** [comment]
I can confirm that this is still an issue when using the forge port of Immersive Portals.

**Comment by williewillus** [comment]
Yes, there's no other known workaround besides removing immersive portals
