### ISSUE TITLE
[1.14] Persistent crashing after Rannuncarpus tried to place Storage Drawer

### ISSUE THREAD

**Issue by aMerryElk** [Vazkii/Botania#3253]
# Version Information
Forge version:  28.2.3
Botania version:  1.11-379

# Further Information

Similar to https://github.com/Vazkii/Quark/issues/2049 except involving a Rannuncarpus instead of a dispenser - and worse, since there's no blacklist option available

Link to crash log: https://gist.github.com/aMerryElk/03846602252e898b96bb72f8c70a80ab
Steps to reproduce:
1.  Throw a storage drawer from the Storage Drawers mod at a Rannuncarpus
2.  Crash
3.  Cry

What I expected to happen:

Rannuncarpus placing storage drawer

What happened instead:

World corruption

Thank you for your time.

**Comment by Hubry** [comment]
World corruption seems to be a big overexaggeration - if you set `removeErroringTileEntities = false` to `true` in `forge-server.toml` in the savefile local config folder, the Rannuncarpus TE should be removed instead of crashing.

Now this crash isn't unique to Botania or Quark - see jaquadro/StorageDrawers#820. The player is explicitly nullable and should've been checked by the other mod, though a bit of safety from our side shouldn't hurt.
