### ISSUE TITLE
[1.15.2] Bore-Magnet Mana lenses can not be combined.

### ISSUE THREAD

**Issue by Trawne** [Vazkii/Botania#3260]
# Version Information
Forge version:  31.1.47
Botania version:  r1.15-382

What I expected to happen: Bore lens and magnet lens to craft into a single lens

What happened instead: Nothing. Other combinations work fine. Specifically bore and magnet lens will not combine regardless of order in crafting grid

**Comment by Hubry** [comment]
Each lens declares a set of properties that it affects, and lenses sharing the property cannot be combined. Some combinations not working is intentional behavior noted in the lexicon:
!["Note that some combinations will not work"](https://user-images.githubusercontent.com/26120076/80136342-d94aac80-85a1-11ea-97f2-a2707abdf47a.png)

The properties can be seen in this part of mod code:
https://github.com/Vazkii/Botania/blob/66388ac52d0f0e59e52bf461cee1c1982db8359c/src/main/java/vazkii/botania/common/item/ModItems.java#L485-L508
More specifically, Bore and Magnet both have the orientation prop, and as such they cannot be combined. The control prop blacklists combinations altogether.
