### ISSUE TITLE
Botania shaders doesn't turn off

### ISSUE THREAD

**Issue by botanyfun** [Vazkii/Botania#3284]
# Version Information
Forge version:  31.1.74
Botania version:  r1.15-383

# Further Information
Mana Pool produces strange shadows from water and some other objects with Sildurs/SEUS shader packs, disable botania shaders in botania-client.toml doesn't work.
Same problem with a glow from chests.

What I expected to happen:
Turning off botania shaders in config removes strange shadows and glow

What happened instead:
Shadows and glow stays
![2020-05-06_21 55 11](https://user-images.githubusercontent.com/64920746/81211424-6b13da00-8fe4-11ea-8a82-39184eb10ba5.png)

**Comment by williewillus** [comment]
if this is through optifine, botania's shaders are already disabled when optifine is detected. this is a separate issue, probably with the shaderpack. the pool water is just a flat texture

**Comment by botanyfun** [comment]
Odd thing is, that i tested it in 1.12 minecraft with this exact shaderpack (Sildurs) and disabling botania shaders in config file did solve the problem. In 1.15.2 on the other hand looks like something stays.

**Comment by alexcraig** [comment]
I'm still experiencing Botania related shader issues with Botania r1.15-384, Forge 31.2.0, and Optifine_1.15.2_HD_U_G1_pre19.

Whenever there is a mana pool nearby, and the mana pool has a non-zero amount of mana in it, I get large shadows with no visible source that move around with my player.

Here's an example (that large, arch shaped shadow shouldn't be there, and it moves around with my player):

![2020-06-04_17 36 25](https://user-images.githubusercontent.com/309733/83813189-e66fb680-a68a-11ea-9b21-278ee2521f24.png)

![2020-06-04_17 36 17](https://user-images.githubusercontent.com/309733/83813200-ebcd0100-a68a-11ea-9bbd-3c7da9cbb8c7.png) 

Here's the same scene after I removed the nearby mana pool in my base:

![2020-06-04_17 37 23](https://user-images.githubusercontent.com/309733/83813345-26369e00-a68b-11ea-8fe8-179760a47d99.png)

These examples are using Nostalgia shader, but the same thing happens with Sildurs. Changing the shaders.enabled config setting has no impact.

**Comment by williewillus** [comment]
then it's not botania's shaders, just the rendering itself. Not much I can do though, the pool water's render is pretty standard as far as renderers go.

**Comment by alexcraig** [comment]
That's too bad. Would it be possible to add a config flag to disable the mana pool rendering entirely? It'd be preferable  to have mana pools always appear as empty rather than having shadows messed up whenever mana pools are nearby.

Also, I tested this out in 1.12.2 with Botania-r.1.10-363 and OptiFine_1.12.2_HD_U_E3. The same issue occurs there, but in 1.12.2 it is fixed by disabling Botania's shaders.

Shaders enabled, no nearby mana pool:

![2020-06-05_05 32 38](https://user-images.githubusercontent.com/309733/83861807-105ac480-a6ef-11ea-95a4-039de73214e5.png)

Shaders enabled, nearby mana pool:

![2020-06-05_05 32 42](https://user-images.githubusercontent.com/309733/83861826-18b2ff80-a6ef-11ea-87f7-ff9c0b1daba1.png)

Shaders disabled, nearby mana pool:

![2020-06-05_05 33 59](https://user-images.githubusercontent.com/309733/83861847-1e104a00-a6ef-11ea-9593-31b1514d67dc.png)
