### ISSUE TITLE
Odd “explosive” Gaia Guardian head rendering.

### ISSUE THREAD

**Issue by GiantLuigi4** [Vazkii/Botania#3324]
I’m working on a mod which adds small scale blocks, and thus I can’t help but notice thar when rendered in small scale, the Gaia Guardian head reacts very “explosively”.
I have absolutely no clue what could possibly cause this, but I think I’ve attached an image of this. (First time putting an image into Github)

I’m not sure if this is fixable in the first place, pretty sure I’m on the lastest botania, and am not sure if this is intended behavior, as I’ve never known what is intended or not with Gaia Guardian.

![BABDAAC7-6CE7-4F2B-96E7-6AEB97582CB5](https://user-images.githubusercontent.com/49770992/84101541-31b3fd00-a9dc-11ea-8efa-6567d4b9f9e8.jpeg)

**Comment by williewillus** [comment]
not sure what you mean?
the gaia guardian head has a shader that makes it distort and wobble

**Comment by GiantLuigi4** [comment]
> not sure what you mean?
> the gaia guardian head has a shader that makes it distort and wobble

Notice how in the lower image, it’s just a bunch of sharp points that don’t even resemble a cube?
Somehow rendering it at 1/256th scale caused that.

**Comment by williewillus** [comment]
oh I see
the vertex shader offsets produces the wobble effect by offsetting the vertices randomly. This displacement is absolute and assumes a "normally" sized gaia head.

Putting the vertices closer together (by shrinking the model) will lead to increased "relatively wobblyness" because an absolute offset is still used.

not sure how I'd address this in a simple manner

**Comment by GiantLuigi4** [comment]
Ah, I have no idea how shaders work.
You know more than I do, lol.

**Comment by williewillus** [comment]
this probably isn't fixable in a simple way, so I'd just live with the jank
