### ISSUE TITLE
minecraft bottles and potions

### ISSUE THREAD

**Issue by TheNimbleNinja** [Vazkii/Botania#3326]
minecraft bottles and potions cant go into the petal apothicary even if you make a recipe with them.

**Comment by Alwinfy** [comment]
Buckets (or other fluid-capable items) can be dropped "into" Apothecary to fill it. So that the Apothecary doesn't eat these items when they're done, all fluid-containers are blacklisted from the Apothecary. (See `vazkii.botania.common.block.tile.TileAltar#collideEntityItem`.) Bottles and potions count as fluid containers.

**Comment by Alwinfy** [comment]
Possible workaround: After fluid-cap check, reject item only if the item cannot be filled with 1000mb of water
