### ISSUE TITLE
botania's shaders cannot be turned off

### ISSUE THREAD

**Issue by rmdyh** [Vazkii/Botania#3347]
# Version Information
Forge version: 31.2.0
Botania version: r1.15-386

# Further Information
I try to turn off botania's shaders by set `[shaders]`'s enabled attribution to false in the config file named 'botania-client', but the shaders of botania's items seem not to be turned off. The scene is also rendered like that in the issue #3338.

**Comment by williewillus** [comment]
which items specifically. this probably has nothing to do with shaders. the config option most definitely works (verifiable with a gpu-call-tracking tool for the super skeptical)

**Comment by rmdyh** [comment]
Mana Pylon, Nature Pylon, and Terrestrial Agglomeration Plate can cause this problem. I'm not sure whether there are more items.
By the way, the Lexica Botania is rendered incorrectly too when players keep it in the hand.
![issue3](https://user-images.githubusercontent.com/31561885/86540184-d3742e80-bf35-11ea-8c56-765f8137faaa.png)

**Comment by Rowantale** [comment]
I can second this issue, but it's mainly a problem when you have your own shaders on. Without other shaders, it works fine for me.
![2020-07-07_15 09 59](https://user-images.githubusercontent.com/41203482/86837052-f997ec80-c063-11ea-9d1d-b2082439f071.png)
![2020-07-07_15 19 48](https://user-images.githubusercontent.com/41203482/86838383-b8084100-c065-11ea-9526-469508e5c9db.png)

I turned off Botania's shaders in the client config, and they still conflict with other shaders. The one I'm using for this particular bug is Chocapic13_V8_Ultra. I suspect part of this may be to do with Optifine being unfinished for 1.15.2, but it is weird that it happens with the Botania config off.

It's the same bug that's always happened when you run shaders with Botania. It's caused by all three pylon types, and the terrestrial agglomeration plate. It affects any block with, I guess for lack of a technical term, fancy models. Chests, mana pools, mana spreaders, banners, just about anything that's not a super simple render. In other mods, Mekanism's wires and the solar panels are effected by it.
I tried re-creating it in a superflat world. If one of those four blocks is within the camera's view, even if it's behind a wall, within 63 (maybe 64) blocks, all "fancy" blocks are affected by this bug. I assume that's simply where Minecraft stops rendering those blocks, regardless of your render distance.

**Comment by rmdyh** [comment]
Yes, I guess shaders may treat these items(all three pylon types and the terrestrial agglomeration plate) as some kind of light source due to some special attributes on these items. And the rendering of some blocks like chests are affected by the light source directly, whether or not there are other blocks between them.
The rendering error itself is caused by shaders, but I think it’s also strange to ask the developers of Optifine to fix rendering problems caused by other mods.
