### ISSUE TITLE
Mana spreader placed directly beneath a mana pool no longer automatically fires into the pool.

### ISSUE THREAD

**Issue by TuckV** [Vazkii/Botania#3377]
Forge version:  forge-31.2.30
Botania version:  Botania-r1.15-387

Steps to reproduce:
1. Place a mana spreader facing upwards.
2. Put mana into the spreader
3. Place a mana pool directly on top of the upwards-facing mana spreader

What I expected to happen:
Mana to fire from the mana spreader into the mana pool.

What happened instead:
Nothing.

**Comment by Killako** [comment]
Its because you placed the pool after the spreader. Spreaders will only auto-detect if the pool is already there when they are first placed. If the pool is placed afterwards, you need to bind the spreader to the pool.

Fix: Use the bind mode on the Wand of the Forest in order to bind the spreader to the pool.
