### ISSUE TITLE
NullPointerException 1.16.2

### ISSUE THREAD

**Issue by Sunekaer** [Vazkii/Botania#3445]
Forge version:  33.0.37
Botania version: 1.16.2-406

# Further Information
Steps to reproduce:
create a world

just some errors from log.
https://paste.sunekaer.com/ulafodiroj.rb

**Comment by Hubry** [comment]
Looks like andersblomqvist/minecraft-well-fed-mod#6. We used to cause this, and it was because the injected loot pools were not named, and if [the ancient 1.14 version of the source code](https://github.com/andersblomqvist/minecraft-well-fed-mod/blob/f099d2e004c5de846f86a931cded028cdca757ea/java/com/branders/wellfedmod/event/EventHandler.java#L138-L174) is pretty much the same as current, they are doing that exact mistake. And it looks like that's a copy of Botania's loot injection code :V
