### ISSUE TITLE
[1.16.2] Crash on world creation

### ISSUE THREAD

**Issue by Silivek** [Vazkii/Botania#3463]
# Version Information
Forge version:  forge-33.0.61
Botania version:  Botania-1.16.2-406

# Further Information
Link to crash log: https://pastebin.com/10Fm2dxe
Steps to reproduce:
1. Create world

What I expected to happen: Create world

What happened instead: Crashed the game

**Comment by Hubry** [comment]
Looks like some mod conflict, some mod does a similiar thing to us but doesn't make everything mutable... which we maybe should've tried to keep in mind, but nobody had any idea how to properly do worldgen when this was done. Forge for 1.16.3 has an event for this since today, and we might update to use that really soon.

You can try working around it by renaming Botania's mod jar to be alphabetically before others, but it might not give any results.

Do you have the actual crash report instead of the game log? That contains the mod list.

**Comment by Silivek** [comment]
Whoops, somehow didn't realize I put the log instead of the crash report. 
Here's the crash report: https://pastebin.com/sNc28XQY

**Comment by Hubry** [comment]
This should be closed already, we moved to Forge's new system since then.
