### ISSUE TITLE
Game crashes when Vivecraft with Forge is used

### ISSUE THREAD

**Issue by utkabulka** [Vazkii/Botania#3494]
# Version Information
Forge version: 1.16.3-forge-34.1.25
Vivecraft version: vivecraft-1.16.3-jrbudda-5-1-forge
Botania version: Any 1.16.x Botania version

# Further Information
Link to crash log: [latest.log](https://gist.github.com/utkabulka/915f5352ec2252fa58954b1a35ef1121)
Steps to reproduce:
1. Install clean Vivecraft 1.16.3 with forge
2. Install any Botania for 1.16
3. Start game with Vivecraft profile
4. Game crashed

What I expected to happen:
Game should start

What happened instead:
Game crashed

Just in case, I'm certain, that Botania mod is causing the crash, because once I remove it from mods folder, vivecraft starts and everything works.

**Comment by Hubry** [comment]
Report this to Vivecraft, this looks like it's caused by their class transformation combined with Mixin and literally any mod using Mixin could result in that crash.

Generally we don't support Optifine here (have you seen how many issues it is introducing nowadays? People get broken worldgen if they combine shaders and Forge. *A graphical enhancement breaking worldgen.*) and Vivecraft is even more hacks on top of Optifine's currently shoddy work.

**Comment by utkabulka** [comment]
Jeez I didn't know Optifine is so poorly written. I guess I'll just wait for a new Vivecraft version and if things stay the same I'll file a report to Vivecraft.

Thank you for your review!
