### ISSUE TITLE
[1.16.4] [FORGE] Ring of Loki multi-place does not work

### ISSUE THREAD

**Issue by RhSm-Firebird** [Vazkii/Botania#3532]
No form of multi place seems to works. Going a block higher than the selected blocks causes the other selections to disappear until I look down at the same level on which I made the selection mesh. No relative placement either. I am sneaking. Have tested in Creative and Survival.

Selection works fine, the mesh is made and it follows my perspective.
Sneak breaking also works fine with Terra Pick and Axe.

Placing is the only problem.

Running Forge 1.16.4 Recommended and Botania 1.16.4 latest.

Please let me know if you need more details. Thanks.

**Comment by williewillus** [comment]
Cannot reproduce

**Comment by HipHopHuman** [comment]
@williewillus I am experiencing this issue as well. I think it may be due to a mod conflict, as I can recall recently testing this with no issues when Botania was installed on it's own (I still want to confirm this later today, however). Please see the below information if it may help.

- **Video demonstration of the issue**: https://streamable.com/r3tlca
- **Minecraft Version**: 1.16.4
- **Forge Version**: 35.1.37
- **Botania Version**:  1.16.4-410
- **List of installed mods**: https://gist.github.com/HipHopHuman/80fbdf23319dbc6a680a0622daffc019
- **Game difficulty**: Normal
- **Game mode**: Survival
- **World type**: Default
- **Singleplayer/Multiplayer**: Singleplayer
- **latest.log**: https://gist.github.com/HipHopHuman/c5d59edd802db52a41c9c075ce2234ae
- **debug.log**: https://gist.github.com/HipHopHuman/ba59964b2cd3ddfae96f54e20fe20d5e

In addition, here are some mods that I suspect to be culprits and why I suspect them:

- **Create**: I suspect Create because it adds The Wand of Symmetry, a tool that serves a similar purpose to the Ring of Loki, perhaps causing a conflict.
- **Double Slabs**: I suspect Double Slabs because it changes the default block placement mechanics to accommodate placing two different slab types in the same block space as well as allowing slabs to be placed vertically.
- **Garden of Glass**: I suspect Garden of Glass because it changes a few mechanics in Botania.
- **Botania Additions**: I suspect Botania Additions because it adds new items and mechanics using Botania's API.
- **Mana Liquidizer (pls no judge)**: I suspect Mana Liquidizer because it adds new items and mechanics using Botania's API.
- **RandomPatches**: I suspect RandomPatches because it changes vanilla behavior slightly.

If needed, I may be able to also provide you with a VisualVM profile of the callstack upon request, but it will have to wait a while as I will be experiencing scheduled national power outages this evening.

**Comment by HipHopHuman** [comment]
Just wrote a long winded description of encountering the same issue, with video demonstration, log files, reproduction steps, modlists, everything. When it turns out I just forgot that I bound my sneak key to Mouse 4. fml. Took me 2 hours to write all that.
