### ISSUE TITLE
Crash rendering Mana Pylon item

### ISSUE THREAD

**Issue by ElvenMythic** [Vazkii/Botania#3554]
[Crash log](https://pastebin.com/AabxRy5w)

Botania seems to crash while rendering the Mana Pylon as an inventory item. I originally discovered this while scrolling through JEI, but even after removing every single mod used except for Botania and its dependencies, any time I tried to get the Mana Pylon it crashed upon rendering.

**Comment by Hubry** [comment]
Usually these kinds of errors are caused by Optifine, but there are no traces of it in this crash report (though a full console log would be useful)... and this instance is very barebones so it really seems like the weirdest issue, and I am starting to suspect the environment you run the game with.

(One thing that seems off is that your mod jar filenames don't have the version number in them, which is usually a sign of using a mod repost website to download, but the versions look recent so this is probably not a worry.)

The thing I am suspecting: you are running Minecraft with OpenJ9 as your JVM, which is *supposed* to [not launch at all](https://github.com/cpw/modlauncher/blob/325de558cd26deb947a3c54176b465d55de16cee/src/main/java/cpw/mods/modlauncher/ValidateLibraries.java#L29-L34) if detected by ModLauncher! In fact it is the very first thing ModLauncher checks.

Could you try to launch the game with a HotSpot based JVM?

**Comment by ElvenMythic** [comment]
Yeah, you're right, it was the JVM, after running the game with the Java bundled with Minecraft.
