### ISSUE TITLE
Client crash rendering Pylons 1.16 on OpenJ9 JVM

### ISSUE THREAD

**Issue by JennyLeeP** [Vazkii/Botania#3647]
# Version Information
Forge version:  35.1.37
Botania version:  botania:1.16.4-411

# Further Information
https://gist.github.com/JennyLeeP/7d9b7aa10323d926923cb6b00d59c117
Steps to reproduce:
1. First step : search "pylon" in JEI or load an area of the world with A pylon placed. 
  I usually only get a "p" typed before crashing.  My friends on the same server do not get this crash. Only appears to happen on 
  my computer.
2. Second step : crash
3. etc...

This render error happens with or without optifine insalled- mentioned because crash report shows I have optifine installed.

What I expected to happen: not crash - I.E render the item in JEI or the World.

What happened instead: crash

Windows 7? NVIDIA ? drivers are up to date. 
Tried deleting everything and reinstalling MC instance, did not work.

**Comment by williewillus** [comment]
give me a crash report without optifine in it then.

**Comment by JennyLeeP** [comment]
for your enjoyment
https://gist.github.com/JennyLeeP/5e3928edf538de680c9f7a7b861dff72

**Comment by xTrM-EN** [comment]
Can reproduce on those same versions.

**Comment by ahdg6** [comment]
Can reproduce on same version,whatever Hotspot or OpenJ9

**Comment by Elopinguwu** [comment]
i beg u to fix it

**Comment by Hubry** [comment]
Everyone who encountered this, please post your crash logs and link the modpacks you use...

**Comment by xTrM-EN** [comment]
I'm using a custom made modpack for 1.16.5 on 36.0.42.
I'm usually recommending my users to use Eclipse OpenJ9 as their JVM as this saves around 800MB of RAM usage.
However, I'm seeing reports of some people not having this problem anymore when switching to Hotspot. I'm currently asking them for more details and I'll be posting them later.

**Comment by Hubry** [comment]
...I haven't noticed the OpenJ9 part... funny, because ModLauncher is supposed to literally *stop the game from launching* if you are using OpenJ9, see [`cpw.mods.modlauncher.ValidateLibraries#validate`](https://github.com/cpw/modlauncher/blob/e9771d85ae2b9118d41a5174dd924825957574e2/src/main/java/cpw/mods/modlauncher/ValidateLibraries.java#L29-L34). The detection is currently broken on AdoptOpenJDK builds though. 

If you can provide crash logs on HotSpot I will be happy to investigate.

**Comment by xTrM-EN** [comment]
Weirdly enough, OpenJ9 seems to be working quite well with modlauncher, it just seems to not like the rendering part of some stuff, including botania pylons (even tho the stacktrace tells the errors line is the... start of a switch statement?).
I had an issue with some item rendering and shaders for items that didn't even use custom rendering, so that might also be the cause.
Anyways, since OpenJ9 is not supported by modlauncher, I'm guessing this won't be resolved unless exactly reproduced on hotspot.

**Comment by JennyLeeP** [comment]
I can confirm that changing from OpenJ9  and using jre1.8.0_281 fixes the issue.
You can likely close this issue if you fee like doing so.
Or look into why it happens with OpenJ9.

Thanks for your time - Jennifer
