### ISSUE TITLE
Game of life Cellular Blocks disappear.

### ISSUE THREAD

**Issue by Droidcrackzz** [Vazkii/Botania#3696]
Hello. Im using Botania with the latest Valhelsia 3 Mod and try to start the Game of life. But every time i place a cellular block on the 25 x 25 Grid, it disappeares after half a second. I dont know what is wrong with it. =(

Botania Version: Botania-1.16.4-413.jar
forge: forge-36.0.46
Valhelsia 3 - 1.16.5

Edit: Multiplayer

Greetings

**Comment by Hubry** [comment]
Is the flower powered by redstone? Because that sounds exactly like it is powered by redstone, since it ticks the board every half second.

**Comment by Droidcrackzz** [comment]
Thanks for the fast reply. I placed a Redstone Torch and a Redstone Block next to the Dandelifeon. Seperatly not both at the same time.

**Comment by Hubry** [comment]
Both of these emit a redstone signal, which would enable the flower.

**Comment by Droidcrackzz** [comment]
Thats right. Its intended to start the Game with this method. But those blocks disappear =(

**Comment by Hubry** [comment]
Screenshots of your setup?

**Comment by BookSerpent** [comment]
I do not work on botania at all, but it sounds like what's happening is that the block is disappearing because of how the flower works. While the flower is powered, every step (half of a second) all blocks that do not have exactly 2 or 3 neighbors will be destroyed, which is intentionally how it works. I would recommend reading the entry in the Lexica Botania on the Dandelifeon. I believe all you need to do is just place more blocks before powering on the Dandelifeon if my understanding is correct.

**Comment by Hubry** [comment]
Yeah, given that I still haven't gotten a response with how the setup looks I'll just close this.
