### ISSUE TITLE
Tons of NullPointerExceptions (incompatibility with Ice and Fire)

### ISSUE THREAD

**Issue by tyggna** [Vazkii/Botania#3805]
# Version Information
Forge version:  36.1.2  
Botania version:  1.16.5-419  

# Further Information
Link to crash log: https://gist.github.com/tyggna/ac6e7b712e9b4915e880dd8d5dd673e9  
I get one of these approximately every 8ms and I suspect that's what's causing frequent lockups in my game.

Steps to reproduce:
Install Botania and Ice and Fire 2.1.8-1.16.5

What I expected to happen:
Either no exceptions are raised, or they are gracefully handled in such a way that they don't completely kill the system.

What happened instead:
Hundreds of NullPointerExceptions each second  (I'll be posting this bug to their mod as well)

**Comment by williewillus** [comment]
can you post a fuller log?

**Comment by lvaleria** [comment]
Not original poster, and my log looks like what they posted but repeated hundreds of times.
From what I could learn it's happening because of something in Citadel version 1.7.2 and above (see [https://github.com/Alex-the-666/Citadel/issues/40](url))
In my experience, the bug happens without botania every few seconds, but something botania does makes it happen twice a second.
