### ISSUE TITLE
Force Relay bug

### ISSUE THREAD

**Issue by LeoBeliik** [Vazkii/Botania#3917]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Botania version

427

### Modloader version

fabric 0.12.12

### Modpack info

botania + deps only

### The latest.log file

https://pastebin.com/dpWebqPS

### Issue description

Relays do be acting weird
https://discord.com/channels/154261184701267969/801591103375015957/934085441907458068

One thing the video doesn't show is that even after the relay stops working, you can keep pushing it normally till it reaches the pos it should be and then starts working again, just a curiosity

### Steps to reproduce

it quite obvious in the vid how to do it

**Comment by TheRealWormbo** [comment]
Can confirm that still happens in the latest 1.20.1 Botania code state, on both Fabric and Forge. Presumably the force relay sees that it's being moved by a piston facing the way the target block ends up moving towards, but it does not take into account that the piston might be retracting, since Force Relays are non-sticky blocks.

Now, the question is, should the force relay figure out it is indirectly being moved by a sticky piston and thus *not* move the target block (to be consistent with its direct pushing effect), or should it support being moved by a retracting sticky piston in a slime block structure?
