### ISSUE TITLE
Cirrus and Nimbus amulets can give an extra jump if timed properly

### ISSUE THREAD

**Issue by LeoBeliik** [Vazkii/Botania#3939]
### Mod Loader

Both Fabric and Forge (I confirm that I have tested both loaders and will specify both loader versions below)

### Minecraft Version

1.18.1

### Botania version

427 & 428-SNAPSHOT

### Modloader version

fabric 0.12.12 & forge 39.0.63

### Modpack info

botania + deps only

### The latest.log file

https://pastebin.com/WFent58p

### Issue description

you can get an extra jump from the Cirrus and Nimbus amulets if timing correctly, is hard to do in fabric but in forge is quite easy.

https://user-images.githubusercontent.com/11804768/151715824-08cacbf2-f679-4c30-a7b7-bbc341696dcc.mp4

https://user-images.githubusercontent.com/11804768/151716073-6cab4272-1dfc-4ad5-97e2-1ff684ecf8e7.mp4

### Steps to reproduce

equip a Cirrus or Nimbus amulet
jump a lot

**Comment by anoomolu** [comment]
I’m able to reproduce this on both Forge and Fabric on 1.19.2-440.

**Comment by TheRealWormbo** [comment]
The reason is likely that usually the amulet logic applies the first "mid-air jump" right as the player jumps from the ground. But occasionally it will not register that as jump, and thus grant an additional mid-air jump.
The cirrus amulet technically grants 2 mid-air jumps, the nimbus amulet even 3. You can see that if you just walk off a ledge, as you are granted that many jumps.
