### ISSUE TITLE
[Bug] On AMD Graphics cards the natura_pylon crashes you

### ISSUE THREAD

**Issue by TheRealM18** [Vazkii/Botania#3959]
### Mod Loader

Fabric

### Minecraft Version

1.18.1

### Botania version

1.18.1-427-FABRIC

### Modloader version

Fabric Loader 0.13.2 + Fabric API 0.46.4+18

### The latest.log file

https://gist.github.com/TheRealM18/31478a95f2b37160b03b795b82d24745

### Issue description

`On testing with scrolling through the REI, and Creative Tabs, It ends up crashing when you get to the natura_pylon.`

### Steps to reproduce

1) Use AMD Drivers
2) Scroll over it
3) Crash

FYI, Does not happen on Nvida Drivers

**Comment by Hubry** [comment]
Are you sure this isn't just Dashloader?

**Comment by TheRealM18** [comment]
It might actually.  I think I launched my pc in AMD mode just now, and it now seems to work fine. Thank you.  If you want to get them involved with the ticket, that would be nice.

**Comment by Hubry** [comment]
I think they are already fixing these, if I remember correctly. This shouldn't be affected by your choice of graphics cards at all, though, the crash is not in shaders but rather an NPE in our code caused by their injections.  
A full log might be more useful here though, chances are that has some more clues... we probably won't spend too much time on Dashloader support, though.
