### ISSUE TITLE
[BUG] Crash with Create

### ISSUE THREAD

**Issue by LunarFactory** [Vazkii/Botania#3966]
### Mod Loader

Forge

### Minecraft Version

1.18.1

### Botania version

1.18.1-428

### Modloader version

Forge 39.0.79

### The latest.log file

https://gist.github.com/PixVoxel/d1c0a89b9857e088fcde5dc438fc738f

### Issue description

When I open ponder of "Portable Storage Interface" in Create mod, It crashed.
It only happened when botania installed.

### Steps to reproduce

1. Install mods(Create, Botania)
2. open ponder which has dropping item scenes
3. crashed.

### Other information

Create 0.4d
Flywheel 0.6.0

**Comment by Wilevar** [comment]
I can second this error. Same situation, the Ponder screen causes client crash "Ticking Screen" issue and references Botania in the crash log. Doesn't happen if Botania is removed, and only happens when a dropped item is rendered in the Ponder scene.

[Pastebin Crash Report](https://pastebin.com/hvjFszMa)

Botania: 429
Create: 0.4d
Flywheel: 0.6.0

**Comment by Hubry** [comment]
Looks like Create is invalidating item entities and then still ticking them? I'd rather have you report to them but I can work around this, I guess

**Comment by williewillus** [comment]
Let's report this to them too.
