### ISSUE TITLE
Pumpkin Seeds not dropping from grass in Garden of Glass

### ISSUE THREAD

**Issue by Its-Adra** [Vazkii/Botania#3970]
### Mod Loader

Forge

### Minecraft Version

1.18.1

### Botania version

1.18.1-429

### Modloader version

Forge 39.0.88

### Modpack info

Custom Modpack

### The latest.log file

https://pastebin.com/MYPA9wdL

### Issue description

I'm unable to gain access to pumpkin seeds through normal Garden of Glass progression. 

Grass, when broken, is only dropping normal seeds. 

### Steps to reproduce

1. Bone meal a Grass Block in a Garden of Glass world
2. Break grass through normal or automated means
3. Only acquire normal seeds and no pumpkin seeds

Attached is an image showing a bone meal dispenser in the background and the results of a hopperhock picking up the drops from grass while I was using the Horn of the Wild.
![Capture](https://user-images.githubusercontent.com/10215750/155872309-2778601f-941d-4487-aafe-d56d9d693949.PNG)

**Comment by potjesoep** [comment]
just encountered this issue on 1.18.2 fabric as well

**Comment by mtmollen** [comment]
I'm seeing the same issue on a 1.18.2 Forge save as well.

As my main save has quite a few mods installed I tested in a new Forge install with the minimum number of mods and had the same issue;

Forge 40.0.44
Botania-1.18.2-430
curios-forge-1.18.2-5.0.6.3
gardenofglass-1.8
Patchouli-1.18.2-67

Steps to reproduce;
1. Enter creative mode
2. Create 10x10 grass island (extended the GoG island)
3. Gave myself 
- Horn of the Wild
- Ring of Magnetization
- Creative Mana Tablet
- Full stack of bone meal
4. Return to Survial mode
5. Apply Bonemeal
6. Use Horn
7. Repeat steps 5 & 6 until bonemeal stack used
8. Check inventory, zero pumpkin seeds


Full log is here;
https://paste.ee/p/BDiW1

**Comment by BenjaminLeSire** [comment]
Same here.

As a workaround until someone more knowledgeable fixes it, adding the drops to the full loot table for grass and tall grass works.

[blocks.zip](https://github.com/VazkiiMods/Botania/files/9014690/blocks.zip)

I tested grass.json, I hope I didn't make mistakes in tall_grass.json.

You can put that in a data pack, in <your pack>/data/minecraft/loot_tables/blocks

It also works with loot_modifiers but it's forge only.

**Comment by Infinidoge** [comment]
Can also reproduce. For fun statistics, I've broken upwards of 1,900 grass and have gotten 0 pumpkin/melon seeds, when I should expect around 60. This occurs with only Botania and Garden of Glass.

**Comment by williewillus** [comment]
I can't get this to happen. It works perfectly in dev for me on both forge or fabric. Can any of you reproduce with just botania and its dependencies?

**Comment by williewillus** [comment]
The drop rate is quite low, but it is there:
![2022-07-22_21 20 33](https://user-images.githubusercontent.com/2015032/180590220-00fb24b5-8096-4ab4-a3b3-ecbcf113daf5.png)

**Comment by Infinidoge** [comment]
I can reproduce in the following setup:
- Fabric 0.14.8 on Minecraft 1.18.2
- Botania 1.18.2 v434
- Garden of Glass 1.8 (based on Jar filename)
- Trinkets 3.3.1
- Fabric API 0.58.0
- Patchouli 71.1

I setup a dispenser to repeatedly bonemeal grass, and punched exactly 5000 tall grass (and 3500 double tall grass):
![image](https://user-images.githubusercontent.com/22727114/180615116-ad3aaf2b-0262-4f95-984c-e60a82870fe8.png)

I received these numbers of wheat seeds, poppies, and dandelions:
![image](https://user-images.githubusercontent.com/22727114/180614844-fbaf3460-742e-4ec7-8288-9d09f6ad0e0c.png)
(If image doesn't load, 1030 wheat seeds, 806 poppies, 440 dandelions)

Alternatively in chest form:
![image](https://user-images.githubusercontent.com/22727114/180614857-4a147bec-3983-4c9b-9a4d-cfd06e3e61c1.png)

This was my setup:
![image](https://user-images.githubusercontent.com/22727114/180614875-7ef0852e-fa0d-437a-b29a-87d2c5e54d60.png)
I wore a greater magnet ring to make sure I got nearly all of the drops, but otherwise had nothing else on my player.


I used over 30 stacks of bonemeal, however my island size was not built to be efficient for bonemeal usage, so that isn't a very useful statistic.

**Comment by williewillus** [comment]
Fixed in GoG v1.9 when it gets approved
