### ISSUE TITLE
Game startup crash

### ISSUE THREAD

**Issue by 624980976** [Vazkii/Botania#3971]
### Mod Loader

Forge

### Minecraft Version

1.18.1

### Botania version

Botania-1.18.1-429

### Modloader version

39.0.88

### Modpack info

personal

### The latest.log file

https://gist.github.com/624980976/454c06d4f1fdad457949f4ec8934475c

### Issue description

Game startup crash:
botania_xplat.mixins.json:client.MixinLevelRenderer

**Comment by williewillus** [comment]
try without optifine please.

**Comment by 624980976** [comment]
I removed optifine and I still had this error

**Comment by Hubry** [comment]
Launch the game with `-Dmixin.dumpTargetOnFailure=true` in your JVM arguments, launch the game, when it crashes zip `.mixin.out` in your game directory and post it here.

**Comment by 624980976** [comment]
[mixin.out.zip](https://github.com/VazkiiMods/Botania/files/8163373/mixin.out.zip)
here

**Comment by Hubry** [comment]
Well, I cannot reproduce this at all. The export would be pointing at Enhanced Celestials, but the bytecode still has the constant in there, and this injection should fail to apply silently instead of crashing.

However I just noticed that the Mixin library version listed is not the officially released Mixin 0.8.5 - the commit hash from the filename in the log points at that commit, but at this point I am convinced this environment has been tampered with - and the directory name mentioning a "custom client" according to Google Translate does not make it sound better.

Download the official Minecraft launcher from [minecraft.net](https://www.minecraft.net/en-us/download), install Forge from their [official download](https://files.minecraftforge.net/net/minecraftforge/forge/index_1.18.1.html), and try again with the same mods. (You can also try something like MultiMC, I guess). If you can reproduce this with a normal environment, I can try looking into it then.
