### ISSUE TITLE
[Feature request] Elementium pickaxe should void deepslate and Tuff

### ISSUE THREAD

**Issue by FizzBuzz3000** [Vazkii/Botania#4032]
### Mod Loader

Both Fabric and Forge (I confirm that I have tested both loaders and will specify both loader versions below)

### Minecraft Version

1.18.2

### Botania version

1.18.2-431

### Modloader version

both

### The latest.log file

'tis a feature request

### Issue description

Title. The elementium pickaxe should void deep slate as it's generally considered a "junk" block and therefore should be voided by the pick.

Putting this here so it doesn't get forgotten on the VM discord.

**Comment by FizzBuzz3000** [comment]
Just remembered that Tuff also exists and is a "junk" block, changed the title to reflect that.

**Comment by Aegide** [comment]
<br>

I found this : 
- Issue : https://github.com/VazkiiMods/Botania/issues/4080
- Commit : https://github.com/VazkiiMods/Botania/commit/6e6f674a2237f7ca921e6889a9659e027b9dd6fd

<br>

Looks like this is fixed in 1.19

![pick](https://user-images.githubusercontent.com/43409914/210182349-af5e966b-2805-4030-b126-5ff0c6c7ca66.gif)

<br>

**Comment by FizzBuzz3000** [comment]
brhu

**Comment by Aegide** [comment]
Unless i didn't understand what you mean 💀 could be possible
