### ISSUE TITLE
Shears still take damage when mining tall mystical flowers (despite not being required anymore)

### ISSUE THREAD

**Issue by Goldenlion5648** [Vazkii/Botania#4104]
### Mod Loader

Forge

### Minecraft Version

1.18.2

### Botania version

1.18.2-434

### Modloader version

40.1.68

### The latest.log file

https://gist.github.com/Goldenlion5648/2d0878b613a14acb46fba8c346ff453e

### Issue description

there was the change recently where tall flowers no longer require shears, but if shears are used, they take durability damage

### Steps to reproduce

1. Mine tall mystical flower with shears
2. Shears lose durability

**Comment by williewillus** [comment]
This is a vanilla bug, you can see it happen in vanilla by just trying to break some carrot crops with shears, the shears get damaged. Since we inherit that code from vanilla, we're affected too. I don't know if a vanilla bug report exists for this, but I'd look for one and file one if there isn't one.

**Comment by Goldenlion5648** [comment]
found the vanilla bug report https://bugs.mojang.com/browse/MC-174829?jql=text%20~%20%22shears%20take%20damage%22%20ORDER%20BY%20affectedVersion%20DESC
