### ISSUE TITLE
Some blocks can't be rotated from the side

### ISSUE THREAD

**Issue by Aegide** [Vazkii/Botania#4201]
### Mod Loader

Fabric

### Minecraft Version

1.19.2

### Botania version

1.19.2-436

### Issue description

The blocks `bellows` and `pump` can't be rotated from the side, only from the top/bottom.

![rotat](https://user-images.githubusercontent.com/43409914/199834656-837c74d1-f054-484b-9fcc-a84eca91093f.gif)

**Comment by TheRealWormbo** [comment]
Some more examples of horizontally rotatable blocks in Botania that ignore rotation clicks on their side faces:

- Fel Pumpkin
- Incence Plate
- Tiny Potato

However, the Livingwood Avatar can be clicked on the side to rotate it, even though it seems to use the same type of property definition.

As far as I can tell, the wand fails to rotate the property value directly and just tells the block state to figure out how to rotate itself by 90 degrees clockwise. The avatar implements that rotation operation, all others mentioned here do not. And since they don't support rotation that way, the attempt returns the original block state and the wand doesn't consider that right-click to be a rotation operation.
