### ISSUE TITLE
Skybox looking funky in 1.19.2 Garden of Glass world

### ISSUE THREAD

**Issue by anoomolu** [Vazkii/Botania#4236]
### Mod Loader

Fabric

### Minecraft Version

1.19.2

### Botania version

Botania-1.19.2-436-FABRIC

### Modloader version

Quilt Loader 0.17.7 / QFAPI 4.0.0-beta.23

### The latest.log file

https://mclo.gs/JQZzi3D

### Issue description

As you can see in the pictures, during the day there are really big shapes on the skybox which aren't supposed to be there. This doesn't happen on a1.18.2 quilt instance with the same mods installed.

![image](https://user-images.githubusercontent.com/77850233/206175283-0028f7b2-1d5e-4eaa-9b25-afe56cf02aa4.png)
![image](https://user-images.githubusercontent.com/77850233/206175632-1bec5268-4efa-4fd1-99e6-3929bf383024.png)

### Steps to reproduce

1. Install Botania + Garden of Glass + Trinkets + Patchouli + QFAPI on Quilt loader
2. Create new gog world
3. Observe as four massive squares present themselves on the skybox.

**Comment by williewillus** [comment]
can you check on fabric and forge as well? It'll help narrow down if it's a fabric, quilt, or vanilla thing

**Comment by anoomolu** [comment]
The problem seems to persist on fabric (loader 0.14.11, api 0.68.0), and interestingly I found a ruined nether portal below a newly generated island).

![image](https://user-images.githubusercontent.com/77850233/206306775-2d8618cf-4c9c-4067-96d4-5e8aa2f87cd9.png)

Skybox also freaks out on forge (41.3.65) and another ruined nether portal found.

Made a new quilt world and found yet another ruined portal.  No clue why this is happening lmao

![image](https://user-images.githubusercontent.com/77850233/206309310-18227398-f504-4388-8910-ac4cae616193.png)

EDIT: made 8 worlds on quilt, 3 of which had a ruined nether portal within 12 chunks of the starting island. The chest always spawns at y=-62.

**Comment by williewillus** [comment]
I don't see this happening in my dev environment.

**Comment by williewillus** [comment]
ok jk, now I do.

**Comment by Svebran** [comment]
While we're at it, structures from the Supplementaries mod and vanila strongholds do appear. I believe the best way to address this issue is to have GoG disable all structures in overworld by default while allowing modpack creators to enable specific ones as they see fit. (Turning them off completely in the world options ruins the gameplay of people who want to access nether fortresses, bastions and end cities). Another solution would be to add recipes and tweak loonium loot tables to turn all vanila structures absolete.
