### ISSUE TITLE
Client crash on startup

### ISSUE THREAD

**Issue by NikeSchuh** [Vazkii/Botania#4246]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-436-FORGE

### Modloader version

Forge: 43.2.0

### The latest.log file

https://pastebin.com/S41e9w1c

### Issue description

Im porting my addon for Botania to 1.19.2. Sadly the game crashes just when starting the game.

### Steps to reproduce

1. Start Minecraft

**Comment by volrathstormborn** [comment]
I have the same issue.

Attaching crash log.
[crash-2022-12-19_20.42.26-client.txt](https://github.com/VazkiiMods/Botania/files/10264058/crash-2022-12-19_20.42.26-client.txt)

**Comment by artemisSystem** [comment]
@rickhovanec, your issue is unrelated. You're using a too low forge version. I think you need at least 43.1.60.

@NikeSchuh i can't immideatly see what the issue is, might need some more info. What version are you porting your addon from? I see you have a released 1.16 version [here](https://www.curseforge.com/minecraft/mc-mods/terra-protector/files). Your main issue seems to be this, though:
`[16Dez.2022 20:10:56.884] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: terraprotector, class de.nike.terraprotector.TerraProtector`,

so the issue may be on your end. To confirm, did you catch that most classes were renamed in the transition from 1.18 to 1.19? (See [these commits](https://github.com/VazkiiMods/Botania/compare/d927a9e1e54f0c1edd7b97fd6bb4a594945acf12...95bd2d3fbc857b7c102687554e1d1b112f8af436))
