### ISSUE TITLE
(Forge 1.19.2) Botania breaks the loom

### ISSUE THREAD

**Issue by Fr0sto** [Vazkii/Botania#4253]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-436

### Modloader version

Forge 43.2.1

### The latest.log file

https://hastebin.com/ixikefivok.sql

### Issue description

The latest version of Botania for Forge 1.19.2 causes the vanilla loom to be nonfunctional. In vanilla MC when you put a dye and a banner into a loom you will be prompted with dozens of patterns to choose from. When Botania is installed, _nothing_ happens. Banner patterning is essentially made impossible.

### Steps to reproduce

1. Install Botania and dependencies on 1.19.2
2. Put a banner and dye into a loom, check if you get the option to select a pattern.

This is what you will see with Botania:
<img width="507" alt="Screenshot 2022-12-24 at 9 55 28 PM" src="https://user-images.githubusercontent.com/15222806/209455978-d0778817-3b22-4023-93df-40add176143c.png">

This is the vanilla behavior (functioning loom):
<img width="506" alt="Screenshot 2022-12-24 at 10 24 19 PM" src="https://user-images.githubusercontent.com/15222806/209456038-93c7213b-d03c-4f07-8c5f-a7a1971de023.png">

**Comment by LeoBeliik** [comment]
This problem comes from botania somehow clearing BannerPatternTags.NO_ITEM_REQUIRED in forge.
removing no_item_required.json from botania jar fixes this problem ~~(of course doing this breaks the mod's banners)~~

Upon further test, I notice that reloading botania's datapack (/datapack disable :botania && /datapack enable :botania) does fix the problem, the mod's banner doesn't work on forge at all.

**Comment by Lucipo** [comment]
Can confirm that issue still persists in 1.19.2-437
![image](https://user-images.githubusercontent.com/36358294/215405596-16753ab1-7368-4e37-8304-13748e8e616d.png)
