### ISSUE TITLE
Shaders making mana in mana pool vanish and given fix to set B:shaders.enabled , no such option exists in config files.

### ISSUE THREAD

**Issue by llloyd4** [Vazkii/Botania#4350]
### Mod Loader

Fabric

### Minecraft Version

1.19.2

### Botania version

1.19.2-438-FABRIC

### Modloader version

Fabric 0.14.19

### Modpack info

https://www.curseforge.com/minecraft/modpacks/all-of-fabric-6

### The latest.log file

https://pastebin.com/DYViqtkW

### Issue description

Config option B:shaders.enabled missing from -client and -common configuration options and mana isn't rendering in the mana pool with Shaders turned on, can't fix it by following the provided instructions here - https://www.complementary.dev/mod-issues/ . Was told on their Discord to ask the devs for further information. 

" Slooshie — Today at 11:14 PM
if the fixes in that list don't fix the botania man pool problem, then you can try asking the dev(s) of the mod to see if they can do anything or look at existing issues (whether open or closed) to see if someone has found a fix "

So... I am asking the devs if there is a fix? I didn't see one when I searched for 'shaders' in Issues. 

### Steps to reproduce

Install AOF6 mod pack (or Botania, Sodium, Iris, Indium, Sodium Extra, Complementary Shaders Reimagined ) 
Fire up Minecraft
Enable Shaders
Ooo, why is my mana pool empty? Oh wait, it isn't! 
Disable Shaders 
Ooo, my mana has returned! 
(Note, sarcasm not necessary, but I hope you get the picture. I did go to the Complementary Shaders Reloaded Discord and was directed to the above fixes web page and told to go here if that didn't work) 

### Other information

Oh Lord. Umm. This be a * big * mod pack. Let me see...

[modlist.txt](https://github.com/VazkiiMods/Botania/files/11360730/modlist.txt)

**Comment by FizzBuzz3000** [comment]
The reason why  mana pools (and mana pylons) vanish is because they use their own shaders, which optifine/iris cannot deal with. A long time ago there *used*  to be an option for a fallback to not use the shaders, but that got removed sometime in the 1.14 port, as there was no real reason to keep it at the time. It's been in debate to bring the option back for a while now in the VM discord, but we'll see.

The Canvas mod, since it completely overhauls the rendering pipeline, DOES allow for the botania shaders for the mana pool/mana pylons to render properly. Note that if you use canvas, you cannot use iris nor sodium. It also is not compatible with iris/optifine shaderpacks. You can get the mod here if you want: https://modrinth.com/mod/canvas

**Comment by williewillus** [comment]
3658e48

**Comment by NateKDavis** [comment]
I am having the same issue in 1.19.2 with Forge. Is there any fix or workaround that isn't "don't use shaders"?

**Comment by Sandriell** [comment]
> I am having the same issue in 1.19.2 with Forge. Is there any fix or workaround that isn't "don't use shaders"?

The option to turn off Botania's specific shaders has been re-added.
