### ISSUE TITLE
Dandelifeon cells at the boundary

### ISSUE THREAD

**Issue by arda-cat** [Vazkii/Botania#4353]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-438

### Modloader version

1.19.2 Forge 43.2.8

### Modpack info

Create Flavoured, with Botania and Immersive Engineering (1.19.2-9.2.-164) added in. Create Flavoured is https://www.curseforge.com/minecraft/modpacks/create-flavored

### The latest.log file

https://pastebin.com/kbmvw5dS

### Issue description

Dandelifeons consider cell blocks outside the range of *any* dandelifeon, active or otherwise, each step. Cells just outside the range of the flower can therefore create cells in range without themselves being able to die, allowing trivial setups like straight lines of 27 cells just out of range to produce ludicrous mana.

This is behaviour is consistent in singleplayer and multiplayer on the modpack I play on, and I'm told the issue is known by developers.

### Steps to reproduce

1. Dandelifeon
2. Cells just out of range
3. Watch'em go

### Other information

I'm StoneColourSkies#7224 on Discord, and I'm in the Violet Moon server. Feel free to ping or DM if I've missed something.

**Comment by yezhiyi9670** [comment]
Can confirm for 1.20.1-443-FORGE. I can reproduce it with just Botania and its required dependencies.

The 1.12.2 and 1.18.2 versions of Botania do not have this issue. I think it is possibly due to the 1.19 change which allows several Dandelifeons to have overlapping working regions as long as they do not work at the same time.

![Game screenshot](https://github.com/VazkiiMods/Botania/assets/39194383/02734f0e-eefe-468d-b44f-8a32a20caa8b)

![Game screenshot](https://github.com/VazkiiMods/Botania/assets/39194383/611f44d6-10ae-4133-a39a-00003fe494bc)

![Demonstration](https://github.com/VazkiiMods/Botania/assets/39194383/73ec38f6-5026-4cf7-be62-c9337c2c0898)
