### ISSUE TITLE
Manasteel Hoe crashes server when used on new block

### ISSUE THREAD

**Issue by TBrauns** [Vazkii/Botania#4357]
### Mod Loader

Forge

### Minecraft Version

1.193.2

### Botania version

1.19.2-438

### Modloader version

Forge 43.2.8

### Modpack info

https://www.curseforge.com/minecraft/modpacks/all-the-mods-8

### The latest.log file

https://pastebin.com/H8Am28WG

### Issue description

Using a Manasteel Hoe to attempt to hoe a new tile crashes the server.

### Steps to reproduce

1. Equip hoe.
2. Look at un-tilled block.
3. Right-click hoe.
4. Server has crashed.

**Comment by williewillus** [comment]
This is an ultra fishy log since nothing in it relates to Botania (rather, it's complaining about logging infrastructure). Can you try:

1. With just Botania and that version of Forge
2. Just Botania and the latest version of Forge
3. The above and the full modpack on a different launcher than the one you're using right now.

**Comment by TBrauns** [comment]
Did #1 first and it worked just fine, so I'm inclined to call this an error in the modpack. Would you agree?

**Comment by williewillus** [comment]
Yeah, sounds like a compatibility issue in the pack.

**Comment by TBrauns** [comment]
I've reported this to the pack's Github.
