### ISSUE TITLE
Elven Mana Spreader inconsistent with other Mana Spreaders

### ISSUE THREAD

**Issue by MysticSloth** [Vazkii/Botania#4458]
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-440

### Modloader version

Forge 43.2.21

### The latest.log file

n/a

### Issue description

I have tested the various tiers of Mana Spreaders, and only the Elven Mana Spreader does not target the Mana Pool directly adjacent to it. The Elven Mana Spreader seems to skip past the Mana Pool directly in front of it and hits the one behind it. It's a minor issue since I can just use the Wand of the Forest to adjust the spreader or place the Spreader at least one block away from the Mana Pool, but the other spreaders function as expected without using the Wand of the Forest. Tested with only Botania and its requisites. 
Screenshot 1 and 4 shows Elven Mana Pool skipping the mana pool in front and delivering mana to the pool behind it. 

![2023-10-06_21 47 12](https://github.com/VazkiiMods/Botania/assets/13672237/86950158-4115-4e44-abc6-dd0d738141c3)
![2023-10-06_21 47 21](https://github.com/VazkiiMods/Botania/assets/13672237/d5236d85-bc77-419b-abd3-6094097a5fa6)
![2023-10-06_21 52 29](https://github.com/VazkiiMods/Botania/assets/13672237/edbabacc-a370-4a95-bb9e-e5c4cff04f82)
![2023-10-06_21 58 31](https://github.com/VazkiiMods/Botania/assets/13672237/ece280ce-3e46-4ecf-a0e4-79640c53580e)

### Steps to reproduce

(1) Place Mana Pool. 
(2) Place Mana Spreader facing Mana Pool.
(3) Elven Mana Spreader does not spread mana to adjacent pool by default unlike other spreaders.

**Comment by anoomolu** [comment]
Can confirm. 
![image](https://github.com/VazkiiMods/Botania/assets/77850233/99ffb071-6778-4a16-bd06-56e06ca32308)

**Comment by TheRealWormbo** [comment]
That's probably some kind of floating point rounding thing. Since all mana burst entities start at exactly the center of a block, it's honestly a small wonder all other spreaders hit the pool by default, even though that ends at exactly half the block height. Maybe the fact that the gaia spreader's burst are exactly double the speed of the livingwood spreaders' is why they behave the same here.

I played around a bit with various burst speed modifiers for the elven spreader, and except for letting the burst entity spawn a bit lower, nothing changes the fact that it misses the first pool.
