### ISSUE TITLE
starcaller particles not rendering

### ISSUE THREAD

**Issue by Elitemagikarp** [Vazkii/Botania#4490]
### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Botania version

1.20.1-441

### Modloader version

Fabric: Loader 0.14.24 API 0.91.0

### Modpack info

using fabulously optimized + botania https://modrinth.com/modpack/fabulously-optimized

### The latest.log file

N/A

### Issue description

the particles that should come from the starcaller do not render

**Comment by anoomolu** [comment]
I'm unable to reproduce this. If you're using shaders, try turning them off and checking again?

**Comment by BookerCatch** [comment]
The particles get culled by EntityCulling. Add "botania:falling_star" to the whitelist in the config.

**Comment by dhouck** [comment]
Thanks for this.  Adding a comment to help people like me searching for this: this also makes the item currently being enchanted by a Botania enchanter invisible, and disabling the mod fixes that too.

Is there somewhere to document a partial incompatibility like this?  I wouldnʼt want it to be marked incompatible in Fabric because in most cases things still work and some people really need the performance boost, but it seems worth mentioning somewhere.
