### ISSUE TITLE
Mana in a Bottle effect replaces any block with water

### ISSUE THREAD

**Issue by numbersguy104** [Vazkii/Botania#4523]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

1.20.1-441

### Modloader version

Forge 47.2.0

### The latest.log file

https://pastebin.com/HyP3YSLq

### Issue description

The Mana in a Bottle effect that places water at the player's location will replace any block, including unbreakable ones. Notably, end portal frames just require standing on top of the block for this to occur.

### Steps to reproduce

1. Stand with your feet positioned inside any block
2. Drink Mana in a Bottle repeatedly until the water effect happens

**Comment by anoomolu** [comment]
Can confirm on Fabric 1.20.1 too, when standing on a not full block like the End Portal Frame mentioned.

**Comment by TheRealWormbo** [comment]
It looks like this bug must have existed in the original mana bottle implementation already. Back then it placed "flowing water", which I assume was a non-source block? At some point it switched to the default water block state, which is a water source block.
Anyway, I think it would be a good idea to treat this effect more like emptying a water bucket at the player's feet (instead of replacing that block to water), potentially waterlogging blocks that support it and otherwise trying to place the water on top of that block, if possible.

**Comment by TheRealWormbo** [comment]
Another bug: If drinking would empty the bottle, but the random effect is to drop the player's inventory, it drops a mana bottle with 1 use left and gives the player an empty bottle.
