### ISSUE TITLE
Botania 1.20.1 Elementium hoe crash (All the mods 9)

### ISSUE THREAD

**Issue by echoptic** [Vazkii/Botania#4534]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

1.20.1-443

### Modloader version

Forge 47.2.16

### Modpack info

https://www.curseforge.com/minecraft/modpacks/all-the-mods-9

### The latest.log file

https://pastebin.com/KQJewJs0

### Issue description

The game crashes when using elementuim hoe

**Comment by echoptic** [comment]
Just checked, its not only Elementium, but manasteel hoe also

**Comment by TheRealWormbo** [comment]
Could you try with a vanilla hoe as well? I have a suspicion this is a conflict with something that modifies how blocks are changed, not necessarily the Botania version of the hoe itself. (I say that because the method mentioned in the crash log isn't even overridden by the Manasteel version of that tool.)

**Comment by echoptic** [comment]
> Could you try with a vanilla hoe as well? I have a suspicion this is a conflict with something that modifies how blocks are changed, not necessarily the Botania version of the hoe itself. (I say that because the method mentioned in the crash log isn't even overridden by the Manasteel version of that tool.)

I already tried vanilla hoes, they dont crash the game.

**Comment by echoptic** [comment]
Some mod adds auto planting seeds with a hoe, could that be interfering somehow?

**Comment by TheRealWormbo** [comment]
Maybe? It's really hard to tell, as the crash itself happens because there appear to be two different class loaders (i.e. the Java Virtual Machine thing that actually loads classes from JAR files) for an unrelated logging library (log4j) that conflict with each other somehow.
Even if the two loaders load the same class from the same JAR file, it will be considered two completely unrelated classes. It looks like a logger loaded by one of those class loaders is trying to process a class loaded by the other class loader. This might be a Forge bug that just happens to be triggered by the Botania hoes for some weird reason. (It should be noted that Botania and many other mods recommend Forge version 47.1.3 for various reasons, which is the last Forge version before the NeoForged fork.)

**Comment by jeremiahwinsley** [comment]
This is not a Botania bug, I've reported this to AIOT Botania: https://github.com/MelanX/aiotbotania/issues/78

**Comment by MelanX** [comment]
Fixed!

**Comment by Serega007RU** [comment]
> Fixed!

How did you solve the problem? I also encountered this problem, but I don't understand how you solved it, please share the solution

**Comment by jeremiahwinsley** [comment]
> > Fixed!
> 
> How did you solve the problem? I also encountered this problem, but I don't understand how you solved it, please share the solution

Just update your pack to the current version, or update AIOT Botania if you are not using ATM9.
