### ISSUE TITLE
Some suggestions for further Botania recipe book/advancement integration

### ISSUE THREAD

**Issue by anoomolu** [Vazkii/Botania#4537]
### Mod Loader

Both Fabric and Forge (I confirm that I have tested both loaders and will specify both loader versions below)

### Minecraft Version

1.20.1

### Botania version

1.20.1-443

### Modloader version

n/a

### The latest.log file

n/a

### Issue description

For the few of us who use the recipe book, Botania dividing its recipes into categories is greatly appreciated. The majority of them are fine, and I'm about to send a patch for a few recipes I was able to adjust myself. I have a few suggestions for some other recipes:

- "Compression" recipes for Manasteel/Terrasteel/Elementium/Mana Diamond/Dragonstone Blocks from DECORATIONS to BUILDING_BLOCKS. Unsure whether Bifrost Blocks should be moved too, given their unusual crafting method.
- Stonecutter recipe advancements (livingrock/shimmerrock/metamorphic rocks/portuguese pavement/corporea decorative blocks/quartzes/azulejos)
- Special floating flowers should be grouped like their natural/glimmering counterparts to reduce bloat.
- Perhaps Redstring, the Pulse Mana Spreader and other functional redstone/Corporea blocks should be moved to the REDSTONE category.
- Rod of the Seas isn't currently part of the equipment tab, changing the category doesn't fix it.

**Comment by TheRealWormbo** [comment]
I'm looking at all of that now and I wonder what Mojang was on when they made that system. The recipe data generator supports 9 different categories in an enum, but actually writes only 4 values of a *different* enum. "building_blocks" becomes "building", "tools" and "combat" becomes "equipment", "redstone" stays "redstone", and everything else becomes "misc".

My thinking here is that we should try moving anything block-like into "building blocks", anything that emits or reacts to redstone signals to "redstone", because that's a relatively small category in vanilla, and anything that even remotely qualifies as a "combat" or "tool" item into those categories. The goal should be to move as much out of the "misc" category as reasonably possible, unless it's expected to be there (e.g. mana pool cart or spectral rail).

Anyway, looking into applying this now. I'll try using the existing patch as basis, but it might have too many conflicts by this time.

**Comment by TheRealWormbo** [comment]
I don't know exactly why the water rod ignores its defined category, but it's likely related to being a non-standard recipe type.
