### ISSUE TITLE
Botania Challenge advancements don't have an experience reward

### ISSUE THREAD

**Issue by anoomolu** [Vazkii/Botania#4544]
### Mod Loader

Both Fabric and Forge (I confirm that I have tested both loaders and will specify both loader versions below)

### Minecraft Version

1.20.1

### Botania version

1.20.1-443

### Modloader version

Forge 47.2.0 / Fabric Loader 0.15.0, API 0.91.0

### The latest.log file

n/a

### Issue description

Most vanilla advancements with the pointy _Challenge_ frame reward experience on completion, varying between 50 and 1000 depending on difficulty. It might be worth giving the Botania challenges experience rewards too. The below values are based on [how much the vanilla advancements give](https://minecraft.wiki/w/Experience)

Blessing, That's Why I Baked Bread, Deja Vu and Decorator can reward either none or 50xp.

Maybe 100xp for At the Mercy of a Dream, then 50xp for the subsequent relic advancements?

100xp for Arithmetic and Invader Girl for the effort involved, and then idk maybe 85 for Out of Step since it's just a bunch of Gaia Spirits really.

A Tale of Six Trillion Years rewards either 100 or 500xp, depends how difficult you consider the task of making an SS Terra Shatterer.

Mythologia's End should be 500xp.

**Comment by TheRealWormbo** [comment]
(Honestly, apart from "Decorator", I do not recognize any of the challenge advancement names.)

All vanilla challenges reward XP, so that's probably not a bad base line for a mod that aims for vanilla balance.

* Base line should be 50 XP, although sort-of trivial ones (portal bread, old flowers, pink wither) might follow the current experimental Blowback advancement and only give 40 XP. (Although I'm not sure why Blowback would give less XP than Return to Sender…)
* I also agree with defeating hard mode being 100 XP and the relics, as a side effect of achieving and repeating that, being 50 XP.
* Defeating hard-mode Gaia Guardian without wearing armor might actually be worth 1k XP, similar to "How Did We Get Here?", but then again, I'm not great at combat, and mods would make this easier. (So maybe 500 XP is the correct amount? This should definitely be the top end of XP rewards.)
* SS-rank Terra Shatterer proves enough dedication to be worth 500 XP, I think.
* I think a big Corporea request would be a bit easier than a max-level Laputa shard, so maybe 65 and 85 XP, respectively?
* Not quite sure where to place the Loki ring usage. I guess it requires a bunch of mana, and figuring out how to provide that many items in one go, so also 85 XP?

~~I also think that, to reduce feel-bads, Blessing could probably be hidden outside the months of June and July.~~
[edit] Nevermind, that property is not dynamic.

**Comment by anoomolu** [comment]
imo the XP granted by the Corporea and Laputa challenges should be swapped - there's not really any effort involved in making a max-level Laputa shard outside of gathering Gaia Spirits

**Comment by TheRealWormbo** [comment]
I guess that's fair. Just had to remind myself how much material you need to collect and store for the Corporea advancement (about 19 double chests of a single item type), so that's a bit more grind than expected. Also, you don't even need to use that max-level shard for the advancement.

**Comment by anoomolu** [comment]
Maybe out of scope for this issue but I wonder whether the laputa shard advancement can/should detect usage?
