### ISSUE TITLE
Chiseled livingrock and metamorphic bricks recipes don't match vanilla

### ISSUE THREAD

**Issue by anoomolu** [Vazkii/Botania#4572]
### Mod Loader

Both Fabric and Forge (I confirm that I have tested both loaders and will specify both loader versions below)

### Minecraft Version

1.20.1

### Botania version

1.20.1-443

### Modloader version

n/a

### The latest.log file

n/a

### Issue description

The recipe for chiseled livingrock and metamorphic bricks doesn't match that of vanilla, nothing that can't be fixed with a datapack temporarily.

Vanilla:
![image](https://github.com/VazkiiMods/Botania/assets/77850233/2700d894-665e-457c-90b1-e0dfbab96b5e)

Botania:
![image](https://github.com/VazkiiMods/Botania/assets/77850233/83973439-da2a-4bdc-bb24-f3e825a18939)

**Comment by TheRealWormbo** [comment]
I assume that's due to the existence of various slab recombination recipes for Botania. While those are nice to have, having vanilla parity for the stone type crafting recipes would probably be better.

Maybe we could also keep the recombination recipes, but modify them to be like the Vanilla Tweaks "Back to Blocks" QoL crafting tweak, which has the slabs arranged horizontally for the recombination recipe.

**Comment by anoomolu** [comment]
I think that's a good idea, and would also have parity with Quark's slab recombination recipes.
