### ISSUE TITLE
Odin's Ring resets HP to base value when returning from extra worlds.

### ISSUE THREAD

**Issue by ArtemMASTER** [Vazkii/Botania#4590]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

1.20.1-444-FORGE-SNAPSHOT

### Modloader version

Forge 47.2.1

### The latest.log file

none

### Issue description

Odin's Ring resets HP to base value when returning from extra worlds.

### Steps to reproduce

1. Let's go to the nether
2. Let's go back

### Other information

https://www.youtube.com/watch?v=Eb1nATj9AIU

**Comment by anoomolu** [comment]
Pretty sure this is a [vanilla issue](https://bugs.mojang.com/browse/MC-17876).

Max Health Fix by Darkhax fixes this issue, but unfortunately doesn't seem to work with Curios/Trinkets, which is why https://modrinth.com/mod/maxhealthfixfixfix is a thing on Fabric. Sadly I don't know any fixes for Forge in the meanwhile

**Comment by TheRealWormbo** [comment]
The Ring of Odin uses attributes to increase the player's health. This particular vanilla bug, [MC-272042](https://bugs.mojang.com/browse/MC-272042), was fixed in Minecraft snapshot 24w21a, and thus will no longer affect the Odin Ring once Botania is ported to 1.21. Since it's no longer worth working around it in Botania itself, I'm closing this issue.
