### ISSUE TITLE
Island type of floating flower is not visible on Forge

### ISSUE THREAD

**Issue by TheRealWormbo** [Vazkii/Botania#4625]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

444-SNAPSHOT

### Modloader version

47.2.0

### The latest.log file

(n/a)

### Issue description

Changing the island type of a floating flower (e.g. via boral seeds or infestation spores) is not visible, even after reloading the chunk. `/data get block` shows that the block entity does correctly change (and reload) the island type, it's just not visible.

**Comment by LeoBeliik** [comment]
I took a look and I think I know why this happening, [getQuads](https://github.com/VazkiiMods/Botania/blob/21c067bd37af5ba17a7cb12597aa681d938896c2/Forge/src/main/java/vazkii/botania/forge/client/ForgeFloatingFlowerModel.java#L160) *always* renders the island type as grass, it never changes, this is because the [modelData](https://github.com/VazkiiMods/Botania/blob/21c067bd37af5ba17a7cb12597aa681d938896c2/Forge/src/main/java/vazkii/botania/forge/client/ForgeFloatingFlowerModel.java#L163) is always empty, thus never goes to the check to change the island type, this was *not* the case on 1.19

**Comment by TheRealWormbo** [comment]
I wonder what's causing that, because I can see it does actually generate the model data when changing island types.
