### ISSUE TITLE
Alfheim portal render on wrong side

### ISSUE THREAD

**Issue by oskarbukovsky** [Vazkii/Botania#4725]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

1.20.1-445-FORGE

### Modloader version

Forge 47.3.1

### The latest.log file

https://gist.github.com/oskarbukovsky/9bfd36ac6f5b315576026f4784b16632

### Issue description

When alfheim portal is build, the portal itself seem to be rendered on wrong side

![image](https://github.com/user-attachments/assets/4cec7a25-ca57-4023-aed0-03b16901ec55)
![image](https://github.com/user-attachments/assets/f94d602a-e0bc-447d-a63a-07106de29b7d)
![image](https://github.com/user-attachments/assets/30a851d6-4964-492b-bb6f-7826a5c0f33d)

**Comment by artemisSystem** [comment]
this was intentional, lol
or at least willie said so. i've grown to like the effect too

**Comment by oskarbukovsky** [comment]
Sorry 😅 i just stumbled upon that and it felt weird

**Comment by TheRealWormbo** [comment]
Maybe it feels weird because the two planes are much farther apart than those of a nether portal. For the Alfheim portal the pixel split is 4/8/4, while it's 6/4/6 for a nether portal. That also makes it feel somewhat strange when the two planes are rendered the "right way around", as they were in 1.12:
![2024-07-19_18 44 43](https://github.com/user-attachments/assets/5b370185-6112-4be9-9a38-587d41e2d1c0)
![2024-07-19_18 44 50](https://github.com/user-attachments/assets/0a77ecdb-725d-457f-8cbe-df1600d794de)
(Also, for some reason one of the planes was double-sided and the other was not? Or both were, but it's a transparency sorting issue.)
