### ISSUE TITLE
 goddess charm doesn't work if you die from the explosion

### ISSUE THREAD

**Issue by LeoBeliik** [Vazkii/Botania#4757]
### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Botania version

1.20.1-446

### Modloader version

Fabric 0.16.5

### The latest.log file

-

### Issue description

In **fabric**, if you die from an explosion whilst wearing the  goddess charm, the terrain gets destroyed, this is **not** the case in forge, if you don't die the charm works as intended

### Steps to reproduce

- equip the  goddess charm
- get a source of mana
- spawn a creeper
- die

blocks are destroyed

**Comment by TheRealWormbo** [comment]
As far as I can tell, this happens because the charm's logic hooks into a later place on Fabric than on Forge, where block damage is prevented before the collected entities are damaged.

There might actually also be an issue on Forge, it's just less obvious. Forge has two different explosion events, and the charm hooks into their common parent class. That means its prevention logic runs once before any block selection has happened, and then again after blocks and entities to damage have been selected. Since the charm doesn't consume mana based on how much damage was prevented, but only based on the fact that an explosion happens, it probably consumes twice the mana on Forge than it uses on Fabric.
