### ISSUE TITLE
Mana spreader suddenly stops working in eternal day mystcraft age

### ISSUE THREAD

**Issue by Entoarox** [Vazkii/Botania#481]
A very basic setup of a flower feeding a spreader, aimed at a mana pool through a detector
After about 7 bursts the following bursts become invisible, and do not trigger the detector.
After about 5 more bursts, the spreader stops sending bursts completely, and simply keeps storing mana
The only way to get the spreader working again is to break and replace it.
I have all of this setup in an eternal day mystcraft age.

Are there any known issues with using mana spreaders in mystcraft ages? Because re-creating the setup in my creative test world's overworld works perfectly fine.

**Comment by Vazkii** [comment]
I haven't tested in mystcraft ages. Any ideas @XCompWiz?

**Comment by XCompWiz** [comment]
My first suspicion is use of total world time client-side. Ages didn't support this until more recently.  This would at least cover pulses rendering funny.
As to the detector, I don't know.  I'd have to know Botania's code-base pretty well to formulate a guess.  Any assumptions you make about dimensions?

**Comment by Entoarox** [comment]
@XCompWiz I'd considered similar, as TWT is not yet in the public release, but I'd think that such an issue would happen immediately, not after a certain amount of pulses work perfectly fine, right? (I'll be honest, I dont really have in-depth knowledge of how they work, it just feels like weird behaviour to me)

**Comment by Vazkii** [comment]
That's the weird part, I don't do any assumptions based on time or the dimension. Relevant classes:
https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/block/tile/mana/TileSpreader.java

**Comment by XCompWiz** [comment]
Ya, you didn't seem like the kind to make unreasonable assumptions, anyway.  I'm not surprised you don't make any. :P
Glancing through that, I can't see anything that strikes me as the root here.  Perhaps best bet would be running with some breakpoints with Mystcraft and Botania in a dev instance. *shrug*  Simply to try and find where it breaks down in logic (assuming it even does).
You want to try stuffing Mystcraft into your mods folder while in dev and see if you can locate it? Seems you would have the best chances, since you know the Botania code base.

From my end I think the easiest way to get a debugable Botania in my dev instance is to clone the repo and make it import my Mystcraft project in Eclipse.  If you don't have any luck (or if you like) I'll try that.

**Comment by IAA-ShRaPNeL** [comment]
I'm having the issue with the spreaders not working, but there's no Mystcraft installed.

**Comment by Vazkii** [comment]
Any update on this?

**Comment by XCompWiz** [comment]
Not from me. :P Does it work better with the latest Mystcraft build? We'll need someone to confirm this.

I still think, if the issue persists, that you'd have the best chances of tracking down what's going on here, as you'd be able to determine what is going wrong within your visuals. Then you could track that back to whatever isn't updating right.  I'm happy to fix whatever it turns out to be, but I can't guess at the root.

**Comment by spacewolfcub** [comment]
Is the OP also running ClearLagg on the server with this issue? Correlation does not denote causality, and I am very familiar with the problem described occurring in the overworld after every time ClearLagg hits. Perhaps this is the true problem and not Mystcraft. Maybe.

In a popular server that I play in, it has been observed that every time ClearLagg happens we all need to leave our home areas until not loaded and then return -- then mana spreaders once again work well. That, or we have to break and replace the spreaders. The problem is worse if we have higher mana production causing very frequent bursts.

The server admins claim that mana bursts cannot be whitelisted in ClearLagg. >.> 
They recommend we put manapools directly adjacent to mana spreaders and use the mana from there so that there is less time that a burst is in the air.

I DIGRESS. The point was, it may not be Mystcraft. It may be the usual problem with ClearLagg.

**Comment by Entoarox** [comment]
I dont have clearLagg installed, mainly because I honestly dont need it as fastCraft is more then enough to keep the tick-rate nice and high (as long as I dont run a lot of AE auto-crafting, but that isnt fastCraft's fault), further, The age in question was a void age with almost no entities, so even if clearLagg was installed, it should not have affected the setup the way it did, especially since the exact same setup in a creative overworld worked perfectly fine without any issues.

**Comment by Vazkii** [comment]
Does it still happen with the chunk checking changes in the latest version?

**Comment by Entoarox** [comment]
I will need to check when I start using it again, the world that had the issues is gone by now due to world-gen related mod-updates that have happened.

**Comment by Vazkii** [comment]
Any updates?

**Comment by Entoarox** [comment]
I've been testing it in any configuration I could think of, and so far it seems to be working perfectly, so it seems to be fixed, even if I have no clue how!
