### ISSUE TITLE
Feature Request: Stone generation

### ISSUE THREAD

**Issue by SynfulChaot** [Vazkii/Botania#487]
Inspired heavily by the Orechid and the Pure Daisy, perhaps there could be a new functional flower that turns the stone blocks around it into random cosmetic worldgen stone variants.

**Comment by Vazkii** [comment]
That's actually a pretty good idea.

**Comment by Barhandar** [comment]
Skypomea/Celestial Glory making AE2's Sky Stone out of normal stone for renewable source of it, anyone? The only uses for it are controllers (and even meteors will last *ages* for that) and no-usage-in-NEI skystone dust, and building since it's a hardy, dark, somewhat smooth blast-resistant material.

**Comment by Durpady** [comment]
While we're at it, how about giving it a list in the config of blocks it can generate?  It'd be cool to have a renewable source of Railcraft's Abyssal and Quarried Stone.

**Comment by Vazkii** [comment]
Closing to make (screen) real estate for bugss as it's an idea, on the todo list already.

**Comment by SynfulChaot** [comment]
I look forward to seeing the implementation.  ^.^
