### ISSUE TITLE
Alf Glass Flasks occasionally use two charges instead of one.

### ISSUE THREAD

**Issue by WolfAmaril** [Vazkii/Botania#519]
I have mostly had this issue with the Flask of Sane Thoughts (can't remember if that's Botania or Forbidden magic.) but I have confirmed the problem exists in vanilla Botania flasks.

**Comment by Vazkii** [comment]
I've seen it a few times already, it's a weird one.

**Comment by netmc** [comment]
This might be the same vanilla issue that causes you to eat two food items occasionally--one about 1/2 second after the first one was consumed.  If you switch to a different hotbar position after you consume the first bit of food, it won't happen.  Some have speculated that this is due to client side lag. If this is the same root cause, I don't think it is fixable.  I see this happen often when I am on my laptop, but rarely when on my much more powerful desktop, so client side lag seems likely.  As far as I can tell, this can happen with all consumable items.

**Comment by WolfAmaril** [comment]
so in short I shoulndn't feel bad about refunding myself brews of sanity.
