### ISSUE TITLE
[REQUEST] Config for 1.8 Stones

### ISSUE THREAD

**Issue by Neodark7** [Vazkii/Botania#752]
Can you add a config option to disable 1.8 stones worldgen cause Chisel 2 and Gany's surface already add them and i don't want to have 3 types of each >.<

**Comment by TheJulianJES** [comment]
I have 4 types :P

**Comment by Neodark7** [comment]
Oh my... I've keep only the chisel one so i can't update botania... But what is your fourth ? :o

**Comment by Entoarox** [comment]
The botania versions dont have worldgen, so why do you need a config for them?

**Comment by Reassembly** [comment]
I'm running (among other mods) Botania, Thaumcraft, and Gany's Surface...
Given that Botania's implementation of 1.8 stone has things like stairs and slabs, but lacks worldgen, I'd rather see something ore-dictionary-ish happen, so that Gany's Surface worldgen'd stone can be more easily used with Botania's recipes. Best of both worlds, then.
I can also see that Gany's Surface prismarine shards are compatible with Botania's recipes, although strangely, prismarine *blocks* aren't recipe-compatible. Maybe whatever part of the implementation is making the prismarine shards compatible could be expanded to make the different varieties of diorite/andesite/granite/basalt interchangeable - at least, until the grand post-1.7.10 migration makes it all moot again?
