### ISSUE TITLE
ItemPhysic keepAlive issue

### ISSUE THREAD

**Issue by CreativeMD** [Vazkii/Botania#784]
Hello,
i'm the author of ItemPhysic and someone reported this bug:
https://github.com/CreativeMD/ItemPhysic/issues/11
Maybe we can fix this issue together, because i have no idea what is going on :D

**Comment by Vazkii** [comment]
Whoever reported that issue is clueless and managed to turn something they don't know into a technical term they pulled out of their ass. Let me translate, your mod doesn't respect getEntityLifespan, a forge method that defines how long an EntityItem can stay in the world for before despawning.
https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/item/equipment/tool/ItemTerraPick.java#L169

**Comment by CreativeMD** [comment]
Oh thank you :D
will fix that.
