### ISSUE TITLE
(180)Step-up reseting when entering world

### ISSUE THREAD

**Issue by MrKunji** [Vazkii/Botania#785]
I have to re-equip the Soujoner's Sash to be able to step up again.
Happens since the update. List of mods, just in case:

![](http://i.imgur.com/Y1hslnb.png)

**Comment by MrKunji** [comment]
Also happens when entering other dimension.

**Comment by Keridos** [comment]
Can confirm this on rv181.

**Comment by Lazersmoke** [comment]
The onEquippedOrLoadedIntoWorld appears to properly set the step height, but the problem is that this function is not run upon being loaded into the world because the getLastPlayerHash function returns the same hash from when the user was previously in the world. The change that broke it was the removal of the aggressive step height adjustment.
