### ISSUE TITLE
Tall Mystical Flower support for Horn of the Wild

### ISSUE THREAD

**Issue by meradz** [Vazkii/Botania#807]
Not sure if this was left out intentionally or not. I think that the Horn of the Wild should be able to properly harvest Tall Mystical Flowers since it is a higher tier item than shears.

Currently: when Horn of the Wild is used on Tall Mystical Flowers, it acts as if the flower was broken by hand or object other than shears and destroys flower.

Proposed change: Horn of the Wild should be able to harvest Tall Mystical Flowers.

**Comment by Vazkii** [comment]
That's a pain to code and it'll clutter your inventory, I'll pass.

**Comment by Barhandar** [comment]
What if HotW drops two regular flowers out of tall flower instead of flat-out destruction?

**Comment by Vazkii** [comment]
That'd require special case code which I don't like.

**Comment by SephirothWS** [comment]
Horn of the Wild already clutters your inventory with seeds and flowers (especially if you're running multiple mods that add additional seed drops to tall grass). ... Horn of the Wild should at least be able to harvest the double-high flowers, or make the double-high flowers ignored by the horn so players could go back with a pair of shears to gather them instead of wasting them.
