### ISSUE TITLE
Boss music does not obey music volume slider

### ISSUE THREAD

**Issue by KaiserYoshi** [Vazkii/Botania#839]
The Gaia Guardian's (incredibly loud) music always plays at full volume regardless of what the "Music" slider under the "Volume and Sounds" options is set to.

Botania r1.6-184
Forge 10.13.3.1387

**Comment by Vazkii** [comment]
It uses the Records slider.

**Comment by zhs2** [comment]
An "I beg to differ" bump. Tested today with r248, no slider I changed (aside from Master) changed the volume of the otherwise incredibly loud boss music. (Cool music anyway.) Either it's broke, or I'm to understand that the volume effect is set when the music actually first plays and can't be further changed?
