### ISSUE TITLE
Pistons can pop off a force relay if there's an unmovable block on the other side

### ISSUE THREAD

**Issue by Azutte** [Vazkii/Botania#916]

**Comment by TheMadmanofChaos** [comment]
Known problem, and is caused by the hacky nature of the block(Forge doesn't have a hook for "Block being pushed by a piston", so some coding magic needs to be used,) Without a proper hook, nothing can really be done to solve this.

This is referenced in the relay's entry. "Furthermore, this block is highly unstable, and may create uncanny effects, care is to be taken,"
