### ISSUE TITLE
Crafty crate stuck when there is no recepie

### ISSUE THREAD

**Issue by devemouse** [Vazkii/Botania#953]
This is more a suggestion: if crafting spaces are full but there is no valid recepie found the crate could just dump all the items on the ground. Right now it is stuck with all items inside and only way to reset it is break and replace.
This should work with Crafting Patterns as well.

Found this while building cake farm. I use the crate with 1x1 crafting pattern to convert sugarcane to sugar. And the issue occurs when some item lands by accident inside hopper above the crate (eg. dirt).

Botania 187.

**Comment by Quezler** [comment]
[this fix does not appear to exist anymore in the 1.16 version](https://github.com/VazkiiMods/Botania/blob/2f106a565965216ee333dab598577fbea1197df5/src/main/java/vazkii/botania/common/block/tile/TileCraftCrate.java#L94) 🤔

**Comment by Hubry** [comment]
It was caught in the crossfire in 3013253c9036106a77b16aaa18a093c517914726 (1.5 years later), and the current state of the lexicon states current behavior as intended.

**Comment by Quezler** [comment]
ah, that's fair i suppose, i did try right clicking it or applying redstone to get it un-stuck, but i forgot to try the wand. 😅

i assumed it was a bug & didn't look further because it seems to consume an astonishingly amount of tps if the recipe is stuck:

basically vanilla + industrial foregoing + botania, shown is a single hopper in it:
![2021-08-15_09 06 47](https://user-images.githubusercontent.com/3179271/129470207-374d8ab6-5760-40fb-b6c9-fc097dfb7eba.png)

and on enigmatica6 where i originally ran into this issue:
![2021-08-13_20 36 33](https://user-images.githubusercontent.com/3179271/129470245-e8d8b2df-613c-4dbe-95fd-e0f7b7c9e7b9.png)

(the visualization is done through [observable](https://www.reddit.com/r/feedthebeast/comments/ouv1az/introducing_observable_a_successor_to_laggoggles/))

my guess is that it tries to craft with the items every tick and doesn't cache its failed status anywhere?
(if the consumed tps were next to 0 i would probably have looked in the book first, but this seemed wrong)

**Comment by Hubry** [comment]
A performance issue deserves a new issue ticket anyways :P 
I'll look into it.
