### ISSUE TITLE
Throwing full stack of iron into mana pool caused iron to get freaky

### ISSUE THREAD

**Issue by SwiftAusterity** [Vazkii/Botania#960]
I had a full (according to the branch) normal mana pool (not elven, not diluted).

I stood on top of it and lobbed an entire stack of vanilla minecraft itemID iron into it.

I got 42 manasteel (with requisite pew pew pew noises and bars bouncing out) and the remainder back in iron.

Went back to my jabba barrel for iron and tried to put the 22 iron back. No dice. Pulled the 34 iron out of the barrel and tried to combine them. No dice. WALIA continued to report that both stacks of iron were vanilla item id iron.

The weird iron was still able to be used in all recipes (that I cared to try) for normal iron ingots. I ended up melting it all in a TiC smeltery and they came out as normal iron bars and blocks.

Not a big deal but it was very weird.

**Comment by MrKunji** [comment]
On wich version? This is the most valuable info.

**Comment by SwiftAusterity** [comment]
Ahh, yes that'd make sense. I got no "you're out of date" messages last night so I believe it is 48/.188.

I'll check the jar name when I get home tonight to confirm.

**Comment by Omnissia** [comment]
You probably kept standing on a mana pool so iron got picked up quicker than finished transforming. The bug with items not being stackable when transformation was unsuccessful was fixed in v.184.

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
