### ISSUE TITLE
Spreaders Stop Recognizing Mana After Server Resets

### ISSUE THREAD

**Issue by Serenity1125** [Vazkii/Botania#963]
So, I'm playing on the technic platform with a pack called CG's Dimensional Dive. There are quite a few other mods in the pack, namely Thaumcraft, MoCreatures, Witchery, and Metallurgy (just putting these here in case the issue is a mod conflict) and the server uses ClearLag (which could also be the culprit I suppose).

As of yesterday, I noticed that after every server restart my spreaders (just normal spreaders; not elven or gaia) would stop recognizing that the flowers around them were producing mana and when I moused over my flowers with the wand of the forest, they were no longer shown as bound to anything. I'm using a tiered Hydroangeas setup with a spreader in the middle (I can send you a photo if needed) so there's a chance it could only be Hydroangeas that are doing this since I haven't tested it with any other flowers. So far the only fix for the problem is either to rebind all the flowers which is a total mess when working with a tiered water setup, or breaking and replacing all of the hydroangeas (which also sucks with 36 flowers and more to come). However, this only solves the problem until the next restart, at which the whole process seems to get jammed up again. Please let me know if you need any photos or more information on the setup. :)

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
