### ISSUE TITLE
Botania armor blocks all damage

### ISSUE THREAD

**Issue by mDiyo** [Vazkii/Botania#964]
Manasteel, Elementium, and Terrasteel armor block all incoming damage regardless of the source. Fall damage, piercing damage, explosions, everything gets blocked where it goes right through everything else.

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*
