### ISSUE TITLE
Dice of Fate not working

### ISSUE THREAD

**Issue by cibastian** [Vazkii/Botania#965]
I have recently installed the latest botania update (r1.6-188) and now when I use the Dice of Fate I always get a 5. I've even gone to creative mode, used the dice and held right click and I only got a five. Killing the Gaia Guardian (2) and getting the dice from him didn't help either.

**Comment by Lazersmoke** [comment]
The result appears to be based on the moon phase. Try using "/time add 24000" and see if it still gives a 5

**Comment by Vazkii** [comment]
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*

**Comment by cibastian** [comment]
that did solve it, I am playing without daylight cycle and so that's why it happened. thanks lazersmoke
